archiexpo.es,"HTTPSConnectionPool(host='archiexpo.es', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
archiexpo.it,"HTTPSConnectionPool(host='archiexpo.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
architectureanddesign.com.au,"HTTPSConnectionPool(host='architectureanddesign.com.au', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.architectureanddesign.com.au', port=443): Read timed out. (read timeout=2)"
arcinfo.ch,"HTTPSConnectionPool(host='arcinfo.ch', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.arcinfo.ch', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))"
arcotampano.it,"HTTPSConnectionPool(host='arcotampano.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0c1fb7fa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='arcotampano.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd0c16f2be0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
arda.or.th,"HTTPSConnectionPool(host='arda.or.th', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.arda.or.th', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
arenas-architecte.com,"HTTPSConnectionPool(host='arenas-architecte.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='arenas-architecte.com', port=443): Read timed out. (read timeout=2)"
argep.hu,"HTTPSConnectionPool(host='argep.hu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='argep.hu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
army.mil,"HTTPSConnectionPool(host='army.mil', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0c1e26490>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='army.mil', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd0c063fa00>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
arnes.si,"HTTPSConnectionPool(host='arnes.si', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0c1ccbac0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='arnes.si', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd0c04efc10>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
articles.co.il,"HTTPSConnectionPool(host='articles.co.il', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='articles.co.il', port=443): Read timed out. (read timeout=2)"
artribune.com,"HTTPSConnectionPool(host='www.artribune.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.artribune.com', port=443): Read timed out. (read timeout=2)"
artun.ee,"HTTPSConnectionPool(host='www.artun.ee', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.artun.ee', port=443): Read timed out. (read timeout=2)"
as-1.co.jp,"HTTPSConnectionPool(host='as-1.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0bfbf7070>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='as-1.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd0bf94ba00>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
asamblea.gob.ni,"HTTPSConnectionPool(host='asamblea.gob.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0bed42dc0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='asamblea.gob.ni', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd0bf11d430>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
asbeiras.pt,"HTTPSConnectionPool(host='www.asbeiras.pt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.asbeiras.pt', port=443): Read timed out. (read timeout=2)"
asfi.gob.bo,"HTTPSConnectionPool(host='asfi.gob.bo', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0bf1927c0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='asfi.gob.bo', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd0bf1928b0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
asklaila.com,"HTTPSConnectionPool(host='asklaila.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'asklaila.com' doesn't match '*.asklaila.com'"")))","HTTPSConnectionPool(host='asklaila.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'asklaila.com' doesn't match '*.asklaila.com'"")))"
askoservering.no,"HTTPSConnectionPool(host='askoservering.no', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))","HTTPSConnectionPool(host='askoservering.no', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))"
asktel.ru,"HTTPSConnectionPool(host='asktel.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='asktel.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
asos.com,"HTTPSConnectionPool(host='www.asos.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.asos.com', port=443): Read timed out. (read timeout=2)"
assabah.com.tn,"HTTPSConnectionPool(host='assabah.com.tn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0c179e370>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='assabah.com.tn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd0bfcf24c0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
assemblee-nationale.fr,"HTTPSConnectionPool(host='assemblee-nationale.fr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0c1228430>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='assemblee-nationale.fr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd0c2351dc0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
astra.co.id,"HTTPSConnectionPool(host='www.astra.co.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.astra.co.id', port=443): Read timed out. (read timeout=2)"
asus.com,"HTTPSConnectionPool(host='asus.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0c0ef3610>: Failed to establish a new connection: [Errno 111] Connection refused'))","('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))"
atauni.edu.tr,"HTTPSConnectionPool(host='atauni.edu.tr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='atauni.edu.tr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
atelier-povetron.cz,"HTTPSConnectionPool(host='atelier-povetron.cz', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0c21e65b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='atelier-povetron.cz', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd0bf8cdac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
atlatszo.hu,"HTTPSConnectionPool(host='atlatszo.hu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='atlatszo.hu', port=443): Read timed out. (read timeout=2)"
au-magasin.fr,"HTTPSConnectionPool(host='au-magasin.fr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fd0c2505460>, 'Connection to au-magasin.fr timed out. (connect timeout=2)'))","HTTPConnectionPool(host='au-magasin.fr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fd0c0b76400>, 'Connection to au-magasin.fr timed out. (connect timeout=2)'))"
aun.edu.eg,"HTTPSConnectionPool(host='aun.edu.eg', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fd0bf179dc0>, 'Connection to aun.edu.eg timed out. (connect timeout=2)'))","HTTPConnectionPool(host='aun.edu.eg', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fd0c1baf880>, 'Connection to aun.edu.eg timed out. (connect timeout=2)'))"
auone.jp,"HTTPSConnectionPool(host='auone.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))","HTTPSConnectionPool(host='auone.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))"
auti.hr,"HTTPSConnectionPool(host='auti.hr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'auti.hr' doesn't match 'www.auti.hr'"")))","HTTPSConnectionPool(host='auti.hr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'auti.hr' doesn't match 'www.auti.hr'"")))"
autojerry.fi,"HTTPSConnectionPool(host='autojerry.fi', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='autojerry.fi', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
autopurkaamot.com,"HTTPSConnectionPool(host='autopurkaamot.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.autopurkaamot.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))"
autostation.com,"HTTPSConnectionPool(host='autostation.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'autostation.com' doesn't match 'www.autostation.com'"")))","HTTPSConnectionPool(host='autostation.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'autostation.com' doesn't match 'www.autostation.com'"")))"
autoszektor.hu,"HTTPSConnectionPool(host='autoszektor.hu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='autoszektor.hu', port=443): Read timed out. (read timeout=2)"
autotrader.co.za,"HTTPSConnectionPool(host='autotrader.co.za', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fd0c213bee0>, 'Connection to autotrader.co.za timed out. (connect timeout=2)'))","HTTPConnectionPool(host='autotrader.co.za', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fd0c0075610>, 'Connection to autotrader.co.za timed out. (connect timeout=2)'))"
autoua.net,"HTTPSConnectionPool(host='autoua.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='autoua.net', port=443): Read timed out. (read timeout=2)"
autozone.com,"HTTPSConnectionPool(host='autozone.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='autozone.com', port=80): Read timed out. (read timeout=2)"
autozone.com.mx,"HTTPSConnectionPool(host='autozone.com.mx', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='autozone.com.mx', port=80): Read timed out. (read timeout=2)"
aviatur.com,"HTTPSConnectionPool(host='www.aviatur.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.aviatur.com', port=443): Read timed out. (read timeout=2)"
avto.net,Exceeded 30 redirects.,Exceeded 30 redirects.
avtomobilizem.com,"HTTPSConnectionPool(host='avtomobilizem.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='avtomobilizem.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
awilime.com,"HTTPSConnectionPool(host='awilime.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'awilime.com' doesn't match either of '*.azurewebsites.net', '*.scm.azurewebsites.net', '*.azure-mobile.net', '*.scm.azure-mobile.net', '*.sso.azurewebsites.net'"")))","HTTPSConnectionPool(host='awilime.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'awilime.com' doesn't match either of '*.azurewebsites.net', '*.scm.azurewebsites.net', '*.azure-mobile.net', '*.scm.azure-mobile.net', '*.sso.azurewebsites.net'"")))"
az-gotvia.bg,"HTTPSConnectionPool(host='www.az-gotvia.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.az-gotvia.bg', port=443): Read timed out. (read timeout=2)"
azoo.hr,"HTTPSConnectionPool(host='azoo.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0b6669ca0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='azoo.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd0b9811e50>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
baac.or.th,"HTTPSConnectionPool(host='baac.or.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0b65f3520>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='baac.or.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd0b65d49d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
babil.com,"HTTPSConnectionPool(host='babil.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.babil.com', port=443): Read timed out. (read timeout=2)"
babnet.net,"HTTPSConnectionPool(host='babnet.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'babnet.net' doesn't match '*.babnet.net'"")))","HTTPSConnectionPool(host='babnet.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'babnet.net' doesn't match '*.babnet.net'"")))"
backapalankavesti.com,"HTTPSConnectionPool(host='backapalankavesti.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='backapalankavesti.com', port=443): Read timed out. (read timeout=2)"
backingtrackx.com,"HTTPSConnectionPool(host='backingtrackx.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='backingtrackx.com', port=80): Read timed out. (read timeout=2)"
bacninh.gov.vn,"HTTPSConnectionPool(host='bacninh.gov.vn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0c1c3c220>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='bacninh.gov.vn', port=80): Read timed out. (read timeout=2)"
bahrain.bh,"HTTPSConnectionPool(host='bahrain.bh', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))","HTTPSConnectionPool(host='bahrain.bh', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))"
balkanspress.com,"HTTPSConnectionPool(host='balkanspress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0c1328670>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='balkanspress.com', port=80): Read timed out. (read timeout=2)"
balticdata.lv,"HTTPSConnectionPool(host='balticdata.lv', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='balticdata.lv', port=80): Read timed out. (read timeout=2)"
bancoestado.cl,"HTTPSConnectionPool(host='bancoestado.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0bcf14d30>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='bancoestado.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd0bfb1efd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
banesco.com,"HTTPSConnectionPool(host='banesco.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0c03eca60>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='banesco.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd0c0c06cd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
bangkokbank.com,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
banglapedia.org,"HTTPSConnectionPool(host='banglapedia.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0c17fcf40>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='banglapedia.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd0b64c6bb0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
bankalfalah.com,"HTTPSConnectionPool(host='bankalfalah.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0bd65b2e0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='bankalfalah.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd0b964e100>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
bankleumi.co.il,"HTTPSConnectionPool(host='bankleumi.co.il', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0b67156d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='bankleumi.co.il', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd0b67150a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
bankofgreece.gr,"HTTPSConnectionPool(host='bankofgreece.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0b9668a60>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='bankofgreece.gr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd0bf1d5cd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
banprogrupopromerica.com.ni,"HTTPSConnectionPool(host='banprogrupopromerica.com.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0c0ce1fd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='banprogrupopromerica.com.ni', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd0bf102490>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
banyuwangikab.go.id,"HTTPSConnectionPool(host='banyuwangikab.go.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='banyuwangikab.go.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
