archiexpo.es,"HTTPSConnectionPool(host='archiexpo.es', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)')))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
archiexpo.it,"HTTPSConnectionPool(host='archiexpo.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)')))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
arcotampano.it,"HTTPSConnectionPool(host='arcotampano.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6631572dc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='arcotampano.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6630deadf0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
arda.or.th,"HTTPSConnectionPool(host='arda.or.th', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.arda.or.th', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
arenas-architecte.com,"HTTPSConnectionPool(host='arenas-architecte.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='arenas-architecte.com', port=443): Read timed out. (read timeout=2)"
argep.hu,"HTTPSConnectionPool(host='argep.hu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='argep.hu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
army.mil,"HTTPSConnectionPool(host='army.mil', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f66319841c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='army.mil', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f662f968a60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
arnes.si,"HTTPSConnectionPool(host='arnes.si', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f662effc9d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='arnes.si', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f662f85ca60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
artesanatopassoapassoja.com.br,"HTTPSConnectionPool(host='artesanatopassoapassoja.com.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6630f4d730>, 'Connection to artesanatopassoapassoja.com.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='artesanatopassoapassoja.com.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f662e9a6ee0>, 'Connection to artesanatopassoapassoja.com.br timed out. (connect timeout=2)'))"
artribune.com,"HTTPSConnectionPool(host='www.artribune.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.artribune.com', port=443): Read timed out. (read timeout=2)"
as-1.co.jp,"HTTPSConnectionPool(host='as-1.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f662e6f9bb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='as-1.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f662e2a9280>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
asamblea.gob.ni,"HTTPSConnectionPool(host='asamblea.gob.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f662fdc6490>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='asamblea.gob.ni', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f663163b7f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
asbeiras.pt,"HTTPSConnectionPool(host='www.asbeiras.pt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.asbeiras.pt', port=443): Read timed out. (read timeout=2)"
asbilligt.se,"HTTPSConnectionPool(host='asbilligt.se', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'asbilligt.se' doesn't match either of 'mail.asbilligt.com', 'mail.asbilligt.se', 'www.asbilligt.com', 'www.asbilligt.se'"")))","HTTPSConnectionPool(host='asbilligt.se', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'asbilligt.se' doesn't match either of 'mail.asbilligt.com', 'mail.asbilligt.se', 'www.asbilligt.com', 'www.asbilligt.se'"")))"
asfi.gob.bo,"HTTPSConnectionPool(host='asfi.gob.bo', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f662e31eeb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='asfi.gob.bo', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f662ea83f70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
asklaila.com,"HTTPSConnectionPool(host='asklaila.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'asklaila.com' doesn't match '*.asklaila.com'"")))","HTTPSConnectionPool(host='asklaila.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'asklaila.com' doesn't match '*.asklaila.com'"")))"
asktel.ru,"HTTPSConnectionPool(host='asktel.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='asktel.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
asos.com,"HTTPSConnectionPool(host='www.asos.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.asos.com', port=443): Read timed out. (read timeout=2)"
assabah.com.tn,"HTTPSConnectionPool(host='assabah.com.tn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f662fbfb5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='assabah.com.tn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f662f3bcbe0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
assemblee-nationale.fr,"HTTPSConnectionPool(host='assemblee-nationale.fr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f662cced2e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='assemblee-nationale.fr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6632058b80>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
astra.co.id,"HTTPSConnectionPool(host='www.astra.co.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.astra.co.id', port=443): Read timed out. (read timeout=2)"
asus.com,"HTTPSConnectionPool(host='asus.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f66317d5f70>: Failed to establish a new connection: [Errno 111] Connection refused'))","('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))"
atauni.edu.tr,"HTTPSConnectionPool(host='atauni.edu.tr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='atauni.edu.tr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
atelier-povetron.cz,"HTTPSConnectionPool(host='atelier-povetron.cz', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f663181d790>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='atelier-povetron.cz', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f662e1c87f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
atlatszo.hu,"HTTPSConnectionPool(host='atlatszo.hu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='atlatszo.hu', port=443): Read timed out. (read timeout=2)"
attivabroker.it,"HTTPSConnectionPool(host='attivabroker.it', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='attivabroker.it', port=80): Read timed out. (read timeout=2)"
auchan.ro,"HTTPSConnectionPool(host='www.auchan.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.auchan.ro', port=443): Read timed out. (read timeout=2)"
aun.edu.eg,"HTTPSConnectionPool(host='aun.edu.eg', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f662f99f1f0>, 'Connection to aun.edu.eg timed out. (connect timeout=2)'))","HTTPConnectionPool(host='aun.edu.eg', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f662b399ac0>, 'Connection to aun.edu.eg timed out. (connect timeout=2)'))"
auti.hr,"HTTPSConnectionPool(host='auti.hr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'auti.hr' doesn't match 'www.auti.hr'"")))","HTTPSConnectionPool(host='auti.hr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'auti.hr' doesn't match 'www.auti.hr'"")))"
autojerry.fi,"HTTPSConnectionPool(host='autojerry.fi', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='autojerry.fi', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
autojournal.cz,"HTTPSConnectionPool(host='www.autojournal.cz', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='autojournal.cz', port=80): Read timed out. (read timeout=2)"
automaailm.ee,"HTTPSConnectionPool(host='automaailm.ee', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='automaailm.ee', port=443): Read timed out. (read timeout=2)"
autopower.bg,"HTTPSConnectionPool(host='autopower.bg', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f662f9a64f0>, 'Connection to autopower.bg timed out. (connect timeout=2)'))","HTTPConnectionPool(host='autopower.bg', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f662df24a90>, 'Connection to autopower.bg timed out. (connect timeout=2)'))"
autorai.nl,"HTTPSConnectionPool(host='autorai.nl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='autorai.nl', port=443): Read timed out. (read timeout=2)"
autoreviu.lt,"HTTPSConnectionPool(host='autoreviu.lt', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f662f35da90>, 'Connection to autoreviu.lt timed out. (connect timeout=2)'))","HTTPConnectionPool(host='autoreviu.lt', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f662b3e6310>, 'Connection to autoreviu.lt timed out. (connect timeout=2)'))"
autostation.com,"HTTPSConnectionPool(host='autostation.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'autostation.com' doesn't match 'www.autostation.com'"")))","HTTPSConnectionPool(host='autostation.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'autostation.com' doesn't match 'www.autostation.com'"")))"
autoszektor.hu,"HTTPSConnectionPool(host='autoszektor.hu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='autoszektor.hu', port=443): Read timed out. (read timeout=2)"
autotrader.co.za,"HTTPSConnectionPool(host='autotrader.co.za', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6629ee5b50>, 'Connection to autotrader.co.za timed out. (connect timeout=2)'))","HTTPConnectionPool(host='autotrader.co.za', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6632077820>, 'Connection to autotrader.co.za timed out. (connect timeout=2)'))"
autozone.com,"HTTPSConnectionPool(host='autozone.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='autozone.com', port=80): Read timed out. (read timeout=2)"
autozone.com.mx,"HTTPSConnectionPool(host='autozone.com.mx', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='autozone.com.mx', port=80): Read timed out. (read timeout=2)"
aviasales.ru,"HTTPSConnectionPool(host='aviasales.ru', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='aviasales.ru', port=80): Read timed out. (read timeout=2)"
avto-fokus.si,"HTTPSConnectionPool(host='avto-fokus.si', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.avto-fokus.si', port=443): Read timed out. (read timeout=2)"
avto.net,Exceeded 30 redirects.,Exceeded 30 redirects.
avtomobilizem.com,"HTTPSConnectionPool(host='avtomobilizem.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='avtomobilizem.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
awilime.com,"HTTPSConnectionPool(host='awilime.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'awilime.com' doesn't match either of '*.azurewebsites.net', '*.scm.azurewebsites.net', '*.azure-mobile.net', '*.scm.azure-mobile.net', '*.sso.azurewebsites.net'"")))","HTTPSConnectionPool(host='awilime.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'awilime.com' doesn't match either of '*.azurewebsites.net', '*.scm.azurewebsites.net', '*.azure-mobile.net', '*.scm.azure-mobile.net', '*.sso.azurewebsites.net'"")))"
az-gotvia.bg,"HTTPSConnectionPool(host='www.az-gotvia.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.az-gotvia.bg', port=443): Read timed out. (read timeout=2)"
azoo.hr,"HTTPSConnectionPool(host='azoo.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6631211640>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='azoo.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f662b61b580>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
b2s.co.th,"HTTPSConnectionPool(host='b2s.co.th', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.b2s.co.th', port=443): Read timed out. (read timeout=2)"
baac.or.th,"HTTPSConnectionPool(host='baac.or.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f662967f0a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='baac.or.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6630359a00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
babil.com,"HTTPSConnectionPool(host='babil.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.babil.com', port=443): Read timed out. (read timeout=2)"
babnet.net,"HTTPSConnectionPool(host='babnet.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'babnet.net' doesn't match '*.babnet.net'"")))","HTTPSConnectionPool(host='babnet.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'babnet.net' doesn't match '*.babnet.net'"")))"
backapalankavesti.com,"HTTPSConnectionPool(host='backapalankavesti.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='backapalankavesti.com', port=443): Read timed out. (read timeout=2)"
bacninh.gov.vn,"HTTPSConnectionPool(host='bacninh.gov.vn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6631e14850>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='bacninh.gov.vn', port=80): Read timed out. (read timeout=2)"
balkanspress.com,"HTTPSConnectionPool(host='balkanspress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6630078c70>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='balkanspress.com', port=80): Read timed out. (read timeout=2)"
bancoestado.cl,"HTTPSConnectionPool(host='bancoestado.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f663134be80>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='bancoestado.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f663054c8e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
banesco.com,"HTTPSConnectionPool(host='banesco.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f662f5e8640>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='banesco.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f662a7f3eb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
bangkokbank.com,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
banglapedia.org,"HTTPSConnectionPool(host='banglapedia.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f66271ff190>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='banglapedia.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6627240a00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
bankalfalah.com,"HTTPSConnectionPool(host='bankalfalah.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6628760f70>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='bankalfalah.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f662f4d48e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
bankleumi.co.il,"HTTPSConnectionPool(host='bankleumi.co.il', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f662f652bb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='bankleumi.co.il', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f662efe50d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
bankofgreece.gr,"HTTPSConnectionPool(host='bankofgreece.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6628943340>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='bankofgreece.gr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6627268220>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
banprogrupopromerica.com.ni,"HTTPSConnectionPool(host='banprogrupopromerica.com.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f662b6551c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='banprogrupopromerica.com.ni', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6631422fa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
banyuwangikab.go.id,"HTTPSConnectionPool(host='banyuwangikab.go.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='banyuwangikab.go.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
