geocities.jp,"HTTPSConnectionPool(host='geocities.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f715119f100>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='geocities.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f715119f8e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
geomedian.com,"HTTPSConnectionPool(host='geomedian.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='geomedian.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
gesetze-im-internet.de,"HTTPSConnectionPool(host='gesetze-im-internet.de', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f71509af9d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='gesetze-im-internet.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f714fb82790>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
gestionderiesgos.gob.ec,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
gesundheitsinformation.de,"HTTPSConnectionPool(host='gesundheitsinformation.de', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f714fb1b460>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='gesundheitsinformation.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f714f613220>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
get.bg,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
getnews.jp,"HTTPSConnectionPool(host='getnews.jp', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='getnews.jp', port=443): Read timed out. (read timeout=2)"
gets.govt.nz,"HTTPSConnectionPool(host='www.gets.govt.nz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.gets.govt.nz', port=443): Read timed out. (read timeout=2)"
geva.co.il,"HTTPSConnectionPool(host='geva.co.il', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.geva.co.il', port=443): Read timed out. (read timeout=2)"
ghafla.com,Exceeded 30 redirects.,Exceeded 30 redirects.
ghidulprimariilor.ro,"HTTPSConnectionPool(host='ghidulprimariilor.ro', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='ghidulprimariilor.ro', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
giaoducthoidai.vn,"HTTPSConnectionPool(host='giaoducthoidai.vn', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='giaoducthoidai.vn', port=443): Read timed out. (read timeout=2)"
gifu.lg.jp,"HTTPSConnectionPool(host='gifu.lg.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f714f5778b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='gifu.lg.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f714c4fe910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
gigabaza.ru,"HTTPSConnectionPool(host='gigabaza.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='gigabaza.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
gismeteo.lt,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
gismeteo.lv,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
gismeteo.pl,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
gismeteo.ru,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
gismeteo.ua,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
giuntialpunto.it,"HTTPSConnectionPool(host='giuntialpunto.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'giuntialpunto.it' doesn't match either of '*.giunti.it', 'giunti.it'"")))","HTTPSConnectionPool(host='www.giuntialpunto.it', port=443): Read timed out. (read timeout=2)"
givatayim.muni.il,"HTTPSConnectionPool(host='givatayim.muni.il', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f7150b83820>, 'Connection to givatayim.muni.il timed out. (connect timeout=2)'))","HTTPConnectionPool(host='givatayim.muni.il', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f714df81340>, 'Connection to givatayim.muni.il timed out. (connect timeout=2)'))"
gizmodo.jp,"HTTPSConnectionPool(host='www.gizmodo.jp', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.gizmodo.jp', port=443): Read timed out. (read timeout=2)"
glasistre.hr,"HTTPSConnectionPool(host='glasistre.hr', port=443): Read timed out.","HTTPConnectionPool(host='glasistre.hr', port=80): Read timed out."
glassumadije.rs,"HTTPSConnectionPool(host='www.glassumadije.rs', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.glassumadije.rs', port=80): Read timed out. (read timeout=2)"
glimp.co.nz,"HTTPSConnectionPool(host='www.glimp.co.nz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.glimp.co.nz', port=443): Read timed out. (read timeout=2)"
gme.cz,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
gnavi.co.jp,"HTTPSConnectionPool(host='www.gnavi.co.jp', port=443): Read timed out. (read timeout=2)","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
gnr.pt,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
gobiernodecanarias.org,"HTTPSConnectionPool(host='gobiernodecanarias.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f714c522be0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='gobiernodecanarias.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f714a861910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
gogov.ru,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
goias.gov.br,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
goldcoastbulletin.com.au,"HTTPSConnectionPool(host='www.goldcoastbulletin.com.au', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.goldcoastbulletin.com.au', port=443): Read timed out. (read timeout=2)"
golos.com.ua,"HTTPSConnectionPool(host='golos.com.ua', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f714d40eeb0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='www.golos.com.ua', port=80): Read timed out. (read timeout=2)"
gomex.rs,"HTTPSConnectionPool(host='gomex.rs', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='gomex.rs', port=443): Read timed out. (read timeout=2)"
gonews.it,"HTTPSConnectionPool(host='www.gonews.it', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.gonews.it', port=443): Read timed out. (read timeout=2)"
goodiz.tv,"HTTPSConnectionPool(host='www.goodiz.tv', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.goodiz.tv', port=443): Read timed out. (read timeout=2)"
googleusercontent.com,"HTTPSConnectionPool(host='googleusercontent.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f714d4024f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='googleusercontent.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7147ee18e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
gorzow.pl,"HTTPSConnectionPool(host='gorzow.pl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7146d80880>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='gorzow.pl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7147ee18b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
gourmet.cl,"HTTPSConnectionPool(host='www.gourmet.cl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.gourmet.cl', port=443): Read timed out. (read timeout=2)"
gov.bc.ca,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
gov.hu,"HTTPSConnectionPool(host='gov.hu', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f714f9096a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='gov.hu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f714930d8b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
gpoint.co.jp,"HTTPSConnectionPool(host='gpoint.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'gpoint.co.jp' doesn't match '*.gpoint.co.jp'"")))","HTTPSConnectionPool(host='gpoint.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'gpoint.co.jp' doesn't match '*.gpoint.co.jp'"")))"
grad-zadar.hr,"HTTPSConnectionPool(host='grad-zadar.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f715031c880>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='grad-zadar.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f714a891400>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
grainger.ca,"HTTPSConnectionPool(host='grainger.ca', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='grainger.ca', port=80): Read timed out. (read timeout=2)"
grainger.com,"HTTPSConnectionPool(host='www.grainger.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.grainger.com', port=443): Read timed out. (read timeout=2)"
grainger.com.mx,"HTTPSConnectionPool(host='grainger.com.mx', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='grainger.com.mx', port=80): Read timed out. (read timeout=2)"
gramatnicaglobuss.lv,"HTTPSConnectionPool(host='gramatnicaglobuss.lv', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.gramatnicaglobuss.lv', port=443): Read timed out. (read timeout=2)"
gravidanzaonline.it,Exceeded 30 redirects.,Exceeded 30 redirects.
grazia.it,"HTTPSConnectionPool(host='grazia.it', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f714391fd30>, 'Connection to grazia.it timed out. (connect timeout=2)'))","HTTPConnectionPool(host='grazia.it', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f714a88ac40>, 'Connection to grazia.it timed out. (connect timeout=2)'))"
graziadaily.co.uk,"HTTPSConnectionPool(host='graziadaily.co.uk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='graziadaily.co.uk', port=443): Read timed out. (read timeout=2)"
grizly.cz,"HTTPSConnectionPool(host='www.grizly.cz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.grizly.cz', port=443): Read timed out. (read timeout=2)"
grizly.sk,"HTTPSConnectionPool(host='www.grizly.sk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.grizly.sk', port=443): Read timed out. (read timeout=2)"
gruene.at,"HTTPSConnectionPool(host='gruene.at', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='gruene.at', port=443): Read timed out. (read timeout=2)"
grupolusofona.pt,"HTTPSConnectionPool(host='grupolusofona.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7149f07370>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='grupolusofona.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f714543d340>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
gsb.or.th,"HTTPSConnectionPool(host='gsb.or.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7148de2580>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='gsb.or.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f714345cbe0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
gtp.gr,"HTTPSConnectionPool(host='gtp.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'gtp.gr' doesn't match either of 'www.gtp.gr', 'news.gtp.gr', 'traveloffers.gtp.gr', 'jobs.gtp.gr', 'about.gtp.gr', 'ferries.gtp.gr'"")))","HTTPSConnectionPool(host='gtp.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'gtp.gr' doesn't match either of 'www.gtp.gr', 'news.gtp.gr', 'traveloffers.gtp.gr', 'jobs.gtp.gr', 'about.gtp.gr', 'ferries.gtp.gr'"")))"
guaranteepra.com,"HTTPSConnectionPool(host='guaranteepra.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f71475b37f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='guaranteepra.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7150550c70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
guarden.co,"HTTPSConnectionPool(host='guarden.co', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='guarden.co', port=80): Read timed out. (read timeout=2)"
guiadasemana.com.br,"HTTPSConnectionPool(host='www.guiadasemana.com.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.guiadasemana.com.br', port=443): Read timed out. (read timeout=2)"
guiadelocio.com,"HTTPSConnectionPool(host='www.guiadelocio.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.guiadelocio.com', port=443): Read timed out. (read timeout=2)"
guiagt.com,"HTTPSConnectionPool(host='guiagt.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='guiagt.com', port=443): Read timed out. (read timeout=2)"
guiato.com.br,"HTTPSConnectionPool(host='guiato.com.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='guiato.com.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
gunadarma.ac.id,"HTTPSConnectionPool(host='gunadarma.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.gunadarma.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
guru.ua,"HTTPSConnectionPool(host='guru.ua', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='guru.ua', port=80): Read timed out. (read timeout=2)"
gyorplusz.hu,"HTTPSConnectionPool(host='www.gyorplusz.hu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.gyorplusz.hu', port=443): Read timed out. (read timeout=2)"
ha.rs,"HTTPSConnectionPool(host='ha.rs', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f7150bd02e0>, 'Connection to ha.rs timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ha.rs', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f714a781730>, 'Connection to ha.rs timed out. (connect timeout=2)'))"
hacienda.go.cr,"HTTPSConnectionPool(host='www.hacienda.go.cr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.hacienda.go.cr', port=443): Read timed out. (read timeout=2)"
hagi.or.id,"HTTPSConnectionPool(host='hagi.or.id', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f71492ce040>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='hagi.or.id', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f71493c0b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
haifa.ac.il,"HTTPSConnectionPool(host='haifa.ac.il', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='haifa.ac.il', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
hakaekonline.com,"HTTPSConnectionPool(host='hakaekonline.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'hakaekonline.com' doesn't match 'www.hakaekonline.com'"")))","HTTPSConnectionPool(host='www.hakaekonline.com', port=443): Read timed out. (read timeout=2)"
hakolhayehudi.co.il,"HTTPSConnectionPool(host='hakolhayehudi.co.il', port=443): Read timed out.","HTTPConnectionPool(host='hakolhayehudi.co.il', port=80): Read timed out."
