handyman.dk,"HTTPSConnectionPool(host='handyman.dk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='handyman.dk', port=443): Read timed out. (read timeout=2)"
hanlefang.net,"HTTPSConnectionPool(host='hanlefang.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16dfe6b310>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='hanlefang.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16df7c9280>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
happyfresh.id,"HTTPSConnectionPool(host='happyfresh.id', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f16dec24b20>, 'Connection to happyfresh.id timed out. (connect timeout=2)'))","HTTPSConnectionPool(host='www.happyfresh.id', port=443): Read timed out. (read timeout=2)"
hardwarehouse.co.th,"HTTPSConnectionPool(host='www.hardwarehouse.co.th', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.hardwarehouse.co.th', port=443): Read timed out. (read timeout=2)"
harpersbazaar.com.sg,"HTTPSConnectionPool(host='harpersbazaar.com.sg', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16df633c40>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='harpersbazaar.com.sg', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16df826bb0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
hasil.gov.my,"HTTPSConnectionPool(host='hasil.gov.my', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f16dec5e880>, 'Connection to hasil.gov.my timed out. (connect timeout=2)'))","HTTPConnectionPool(host='hasil.gov.my', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f16de604550>, 'Connection to hasil.gov.my timed out. (connect timeout=2)'))"
hattonplantations.lk,"HTTPSConnectionPool(host='hattonplantations.lk', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='hattonplantations.lk', port=80): Read timed out. (read timeout=2)"
hayat.ba,"HTTPSConnectionPool(host='hayat.ba', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='hayat.ba', port=443): Read timed out. (read timeout=2)"
hazu.hr,"HTTPSConnectionPool(host='hazu.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16dd4468b0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='hazu.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16dd185fa0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
hcmcpv.org.vn,"HTTPSConnectionPool(host='hcmcpv.org.vn', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))","HTTPSConnectionPool(host='hcmcpv.org.vn', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))"
hdmall.id,"HTTPSConnectionPool(host='hdmall.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='hdmall.id', port=443): Read timed out. (read timeout=2)"
hebramusic.be,"HTTPSConnectionPool(host='hebramusic.be', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16de1acfd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='hebramusic.be', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16df0f8e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
heiwerken-pvantwout.nl,"HTTPSConnectionPool(host='heiwerken-pvantwout.nl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16df37fd90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))","HTTPConnectionPool(host='heiwerken-pvantwout.nl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16dd219b50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"
hektapatur.no,"HTTPSConnectionPool(host='hektapatur.no', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f16df551d30>, 'Connection to hektapatur.no timed out. (connect timeout=2)'))","HTTPConnectionPool(host='hektapatur.no', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f16dc1051f0>, 'Connection to hektapatur.no timed out. (connect timeout=2)'))"
hellopro.fr,"('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect data check'))","('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect data check'))"
helwan.edu.eg,"HTTPSConnectionPool(host='helwan.edu.eg', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16db387e20>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))","HTTPConnectionPool(host='helwan.edu.eg', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16e018d1f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"
hemat.id,"HTTPSConnectionPool(host='www.hemat.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.hemat.id', port=443): Read timed out. (read timeout=2)"
heritagehomestayhoian.com,"HTTPSConnectionPool(host='heritagehomestayhoian.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16decbc490>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='heritagehomestayhoian.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16df979460>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
heute-lernen.de,"HTTPSConnectionPool(host='heute-lernen.de', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'heute-lernen.de' doesn't match either of '*.spotlight-verlag.de', 'spotlight-verlag.de'"")))","HTTPSConnectionPool(host='heute-lernen.de', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'heute-lernen.de' doesn't match either of '*.spotlight-verlag.de', 'spotlight-verlag.de'"")))"
hibid.com,"HTTPSConnectionPool(host='hibid.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='hibid.com', port=443): Read timed out. (read timeout=2)"
hikaritv.net,"HTTPSConnectionPool(host='hikaritv.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16da7e7d00>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='hikaritv.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16db49faf0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
hilton.com,"HTTPConnectionPool(host='www.hilton.com', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.hilton.com', port=80): Read timed out. (read timeout=2)"
hiper.rs,"HTTPSConnectionPool(host='www.hiper.rs', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.hiper.rs', port=443): Read timed out. (read timeout=2)"
hipercor.es,"HTTPSConnectionPool(host='hipercor.es', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'hipercor.es' doesn't match either of 'elcorteingles.com', 'www.elcorteingles.com'"")))","HTTPSConnectionPool(host='www.hipercor.es', port=443): Read timed out. (read timeout=2)"
hirnavigator.hu,"HTTPSConnectionPool(host='hirnavigator.hu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='hirnavigator.hu', port=443): Read timed out. (read timeout=2)"
hiroshima-u.ac.jp,"HTTPSConnectionPool(host='hiroshima-u.ac.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16decbcbe0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='hiroshima-u.ac.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16e00cd490>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
hiroshima.lg.jp,"HTTPSConnectionPool(host='hiroshima.lg.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16dcdcdd00>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='hiroshima.lg.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16dd23fa00>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
hiru.eus,"HTTPSConnectionPool(host='hiru.eus', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16db082ee0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='hiru.eus', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16deacfeb0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
hmg.com.sa,"HTTPSConnectionPool(host='hmg.com.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='hmg.com.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
hmv.co.jp,"HTTPSConnectionPool(host='hmv.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'hmv.co.jp' doesn't match 'www.hmv.co.jp'"")))","HTTPConnectionPool(host='hmv.co.jp', port=80): Read timed out. (read timeout=2)"
hoanmysaigon.com,"HTTPSConnectionPool(host='hoanmysaigon.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.hoanmysaigon.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
hok.hr,"HTTPSConnectionPool(host='hok.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16da8a28e0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='hok.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16df96c430>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
hokkaido.lg.jp,"HTTPSConnectionPool(host='hokkaido.lg.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16db845850>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='hokkaido.lg.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16db3126d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
hokudai.ac.jp,"HTTPSConnectionPool(host='hokudai.ac.jp', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f16dda33940>, 'Connection to hokudai.ac.jp timed out. (connect timeout=2)'))","HTTPConnectionPool(host='hokudai.ac.jp', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f16de07f370>, 'Connection to hokudai.ac.jp timed out. (connect timeout=2)'))"
holon.muni.il,"HTTPSConnectionPool(host='holon.muni.il', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f16dfb73c70>, 'Connection to holon.muni.il timed out. (connect timeout=2)'))","HTTPConnectionPool(host='holon.muni.il', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f16dd0e1dc0>, 'Connection to holon.muni.il timed out. (connect timeout=2)'))"
homedepot.ca,"HTTPSConnectionPool(host='homedepot.ca', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='homedepot.ca', port=80): Read timed out. (read timeout=2)"
homedepot.com,"HTTPSConnectionPool(host='www.homedepot.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.homedepot.com', port=443): Read timed out. (read timeout=2)"
honda.co.jp,"HTTPSConnectionPool(host='honda.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16d7a02c70>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='honda.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16db4f2940>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
hops.id,"HTTPSConnectionPool(host='www.hops.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.hops.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
hortes.ee,"HTTPSConnectionPool(host='hortes.ee', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='hortes.ee', port=443): Read timed out. (read timeout=2)"
hosp.go.jp,"HTTPSConnectionPool(host='hosp.go.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16df5cb5e0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='hosp.go.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16d7caeee0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
hospital-mmk.ru,"HTTPSConnectionPool(host='hospital-mmk.ru', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='hospital-mmk.ru', port=80): Read timed out. (read timeout=2)"
hot.net.il,Exceeded 30 redirects.,Exceeded 30 redirects.
hotbak.net,"HTTPSConnectionPool(host='hotbak.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16dac8fb50>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='hotbak.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16d79d6c10>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
hottomotto.com,"HTTPSConnectionPool(host='hottomotto.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16d4122070>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='hottomotto.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16df52dbb0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
hotwire.com,"HTTPSConnectionPool(host='www.hotwire.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.hotwire.com', port=443): Read timed out. (read timeout=2)"
houseoffraser.co.uk,"HTTPSConnectionPool(host='houseoffraser.co.uk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')))","HTTPConnectionPool(host='houseoffraser.co.uk', port=80): Read timed out. (read timeout=2)"
houzz.co.uk,"HTTPSConnectionPool(host='www.houzz.co.uk', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.houzz.co.uk', port=80): Read timed out. (read timeout=2)"
houzz.com,"HTTPSConnectionPool(host='www.houzz.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.houzz.com', port=443): Read timed out. (read timeout=2)"
houzz.com.au,"HTTPSConnectionPool(host='www.houzz.com.au', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.houzz.com.au', port=443): Read timed out. (read timeout=2)"
houzz.de,"HTTPSConnectionPool(host='www.houzz.de', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.houzz.de', port=443): Read timed out. (read timeout=2)"
houzz.dk,"HTTPSConnectionPool(host='www.houzz.dk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.houzz.dk', port=443): Read timed out. (read timeout=2)"
houzz.es,"HTTPSConnectionPool(host='www.houzz.es', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.houzz.es', port=443): Read timed out. (read timeout=2)"
houzz.fr,"HTTPSConnectionPool(host='www.houzz.fr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.houzz.fr', port=443): Read timed out. (read timeout=2)"
houzz.ie,"HTTPSConnectionPool(host='www.houzz.ie', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.houzz.ie', port=443): Read timed out. (read timeout=2)"
houzz.it,"HTTPSConnectionPool(host='www.houzz.it', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.houzz.it', port=443): Read timed out. (read timeout=2)"
hovamenjek.hu,"HTTPSConnectionPool(host='hovamenjek.hu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='hovamenjek.hu', port=443): Read timed out. (read timeout=2)"
hrsume.hr,"HTTPSConnectionPool(host='hrsume.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16deb84a30>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='hrsume.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16dbfc2fa0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
hua.gr,"HTTPSConnectionPool(host='hua.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16d7ce8b50>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='hua.gr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16d739e0a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
huffingtonpost.it,"HTTPSConnectionPool(host='huffingtonpost.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16da5606d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='huffingtonpost.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16e036bd60>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
humaninc.nl,"HTTPSConnectionPool(host='humaninc.nl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16dffc1850>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))","HTTPConnectionPool(host='humaninc.nl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16d7cae6d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"
hyogo.lg.jp,"HTTPSConnectionPool(host='hyogo.lg.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16ddee4a90>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='hyogo.lg.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16d74cd370>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
hzz.hr,"HTTPSConnectionPool(host='hzz.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16dea540a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='hzz.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16df0b3880>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
hzzo-net.hr,"HTTPSConnectionPool(host='hzzo-net.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16de36eaf0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='hzzo-net.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16de937670>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
