irishstatutebook.ie,"HTTPSConnectionPool(host='irishstatutebook.ie', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f830e2eabe0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='irishstatutebook.ie', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f830de97190>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
irisplaza.co.jp,"HTTPSConnectionPool(host='irisplaza.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f830e122e50>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='irisplaza.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f830de6cfa0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
irk.ru,"HTTPSConnectionPool(host='www.irk.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.irk.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))"
irr.ru,Exceeded 30 redirects.,Exceeded 30 redirects.
isa.gov.il,"HTTPSConnectionPool(host='isa.gov.il', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f830de4c850>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='isa.gov.il', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f830d722820>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
isi.ac.id,"HTTPSConnectionPool(host='isi.ac.id', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='isi.ac.id', port=80): Read timed out. (read timeout=2)"
islamstory.com,"HTTPSConnectionPool(host='islamstory.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='islamstory.com', port=80): Read timed out. (read timeout=2)"
israelalbum.org.il,"HTTPSConnectionPool(host='israelalbum.org.il', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'israelalbum.org.il' doesn't match either of 'infocenters.co.il', 'www.infocenters.co.il'"")))","HTTPConnectionPool(host='www.israelalbum.org.il', port=80): Read timed out. (read timeout=2)"
iss.it,"HTTPSConnectionPool(host='iss.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f830b542e80>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='iss.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f830c480280>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
istanbulc.edu.tr,"HTTPSConnectionPool(host='istanbulc.edu.tr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='istanbulc.edu.tr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
istanbulkitapcisi.com,"HTTPSConnectionPool(host='istanbulkitapcisi.com', port=443): Read timed out.","HTTPConnectionPool(host='istanbulkitapcisi.com', port=80): Read timed out. (read timeout=2)"
itau.com.uy,"HTTPSConnectionPool(host='itau.com.uy', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f830b6b0ee0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='itau.com.uy', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f830b424a00>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
its-mo.com,"HTTPSConnectionPool(host='its-mo.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f830a433160>: Failed to establish a new connection: [Errno 113] No route to host'))","HTTPConnectionPool(host='its-mo.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f830b125d90>: Failed to establish a new connection: [Errno 113] No route to host'))"
itsvet.com,"HTTPSConnectionPool(host='itsvet.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='itsvet.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
itu.org.il,"HTTPSConnectionPool(host='itu.org.il', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='itu.org.il', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
iu.edu.jo,"HTTPSConnectionPool(host='iu.edu.jo', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='iu.edu.jo', port=443): Read timed out. (read timeout=2)"
ivivu.com,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
ivote.co.za,"HTTPSConnectionPool(host='ivote.co.za', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.ivote.co.za', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
iww.de,"HTTPSConnectionPool(host='www.iww.de', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.iww.de', port=443): Read timed out. (read timeout=2)"
izletnadlani.com,"HTTPSConnectionPool(host='izletnadlani.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='izletnadlani.com', port=443): Read timed out. (read timeout=2)"
jadrolinija.hr,"HTTPSConnectionPool(host='jadrolinija.hr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f830c889820>, 'Connection to jadrolinija.hr timed out. (connect timeout=2)'))","HTTPConnectionPool(host='jadrolinija.hr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f830b11c5b0>, 'Connection to jadrolinija.hr timed out. (connect timeout=2)'))"
jaf.mil.jo,"HTTPSConnectionPool(host='jaf.mil.jo', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='jaf.mil.jo', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
janisroze.lv,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
japanpost.jp,"HTTPSConnectionPool(host='japanpost.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f830a28ed30>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='japanpost.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f830a2c1fa0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
jatimprov.go.id,"HTTPSConnectionPool(host='jatimprov.go.id', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='jatimprov.go.id', port=80): Read timed out."
javerianacali.edu.co,"HTTPSConnectionPool(host='javerianacali.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f830caa6370>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='javerianacali.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f830ba5fe80>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
jawharati.ma,"HTTPSConnectionPool(host='jawharati.ma', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'jawharati.ma' doesn't match either of '*.web-hosting.com', 'web-hosting.com'"")))","HTTPSConnectionPool(host='jawharati.ma', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'jawharati.ma' doesn't match either of '*.web-hosting.com', 'web-hosting.com'"")))"
jcpenney.com,"HTTPConnectionPool(host='www.jcpenney.com', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.jcpenney.com', port=80): Read timed out. (read timeout=2)"
jelgavniekiem.lv,"HTTPConnectionPool(host='www.jelgavniekiem.lv', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.jelgavniekiem.lv', port=80): Read timed out. (read timeout=2)"
jenatadnes.com,"HTTPSConnectionPool(host='www.jenatadnes.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.jenatadnes.com', port=443): Read timed out. (read timeout=2)"
jenite.bg,"HTTPSConnectionPool(host='jenite.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='jenite.bg', port=443): Read timed out. (read timeout=2)"
jetro.go.jp,"HTTPSConnectionPool(host='jetro.go.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8308a85d90>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='jetro.go.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f830c60fc40>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
jgypk.hu,"HTTPSConnectionPool(host='jgypk.hu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'jgypk.hu' doesn't match either of '*.mediacenter.hu', 'mediacenter.hu'"")))",Exceeded 30 redirects.
jica.go.jp,"HTTPSConnectionPool(host='jica.go.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f830dff93d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='jica.go.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f830c72e2e0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
jimhorsfield.com,"HTTPSConnectionPool(host='jimhorsfield.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f830be71be0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='jimhorsfield.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f830bc22550>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
jma.go.jp,"HTTPSConnectionPool(host='jma.go.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f830d5f5ee0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='jma.go.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8309adb250>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
jobkarov.com,"HTTPSConnectionPool(host='jobkarov.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='jobkarov.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f830d489610>: Failed to establish a new connection: [Errno 113] No route to host'))"
jobscentral.com.sg,"HTTPSConnectionPool(host='jobscentral.com.sg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='jobscentral.com.sg', port=443): Read timed out. (read timeout=2)"
jobsite.co.uk,"HTTPSConnectionPool(host='www.jobsite.co.uk', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.jobsite.co.uk', port=80): Read timed out. (read timeout=2)"
jobtopgun.com,"HTTPSConnectionPool(host='jobtopgun.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.jobtopgun.com', port=443): Read timed out. (read timeout=2)"
jobzaty.com,"HTTPSConnectionPool(host='www.jobzaty.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.jobzaty.com', port=443): Read timed out. (read timeout=2)"
jotainmaukasta.fi,"HTTPSConnectionPool(host='jotainmaukasta.fi', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='jotainmaukasta.fi', port=80): Read timed out. (read timeout=2)"
joy.ne.jp,"HTTPSConnectionPool(host='joy.ne.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f830649c1c0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='joy.ne.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f830cccecd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
jpa.gov.my,"HTTPSConnectionPool(host='jpa.gov.my', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f830db38f70>, 'Connection to jpa.gov.my timed out. (connect timeout=2)'))","HTTPConnectionPool(host='jpa.gov.my', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8307110040>, 'Connection to jpa.gov.my timed out. (connect timeout=2)'))"
jpn.org,"HTTPSConnectionPool(host='jpn.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f830c480f10>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='jpn.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8308b68760>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
jpnumber.com,"HTTPSConnectionPool(host='jpnumber.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f830b936d00>, 'Connection to jpnumber.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='jpnumber.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f83079b8340>, 'Connection to jpnumber.com timed out. (connect timeout=2)'))"
jr-odekake.net,"HTTPSConnectionPool(host='jr-odekake.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f830cd2d520>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='jr-odekake.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f830632a490>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
jreast.co.jp,"HTTPSConnectionPool(host='jreast.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f830d9a2eb0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='jreast.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8309e61e80>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
js88.com,"HTTPSConnectionPool(host='js88.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f830894c850>, 'Connection to js88.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='js88.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8307101e50>, 'Connection to js88.com timed out. (connect timeout=2)'))"
jst.go.jp,"HTTPSConnectionPool(host='jst.go.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f830d0cfcd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='jst.go.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8308a52dc0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
jtb.co.jp,"HTTPSConnectionPool(host='jtb.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))","HTTPConnectionPool(host='www.jtb.co.jp', port=80): Read timed out. (read timeout=2)"
jtconsulting.be,"HTTPSConnectionPool(host='jtconsulting.be', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f830d37a4c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='jtconsulting.be', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f830d9a2b20>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
juduo.cc,"HTTPSConnectionPool(host='juduo.cc', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.juduo.cc', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
jujuy.gob.ar,"HTTPSConnectionPool(host='jujuy.gob.ar', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))","HTTPConnectionPool(host='jujuy.gob.ar', port=80): Read timed out. (read timeout=2)"
jukeboxdiner.com,"HTTPSConnectionPool(host='jukeboxdiner.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='jukeboxdiner.com', port=80): Read timed out. (read timeout=2)"
jumsinfo.lt,"HTTPSConnectionPool(host='jumsinfo.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')))","HTTPConnectionPool(host='www.jumsinfo.lt', port=80): Read timed out. (read timeout=2)"
jurbarkosviesa.lt,"HTTPSConnectionPool(host='jurbarkosviesa.lt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='jurbarkosviesa.lt', port=443): Read timed out. (read timeout=2)"
juridicas.com,"HTTPSConnectionPool(host='juridicas.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'juridicas.com' doesn't match either of 'noticias.juridicas.com', 'www.noticias.juridicas.com'"")))","HTTPSConnectionPool(host='juridicas.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'juridicas.com' doesn't match either of 'noticias.juridicas.com', 'www.noticias.juridicas.com'"")))"
jurisprudencia.gob.sv,"HTTPSConnectionPool(host='jurisprudencia.gob.sv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f830532fb50>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='jurisprudencia.gob.sv', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f830dac0d90>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
juritravail.com,"HTTPSConnectionPool(host='www.juritravail.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.juritravail.com', port=443): Read timed out. (read timeout=2)"
just.ro,"HTTPSConnectionPool(host='just.ro', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f83053c90a0>, 'Connection to just.ro timed out. (connect timeout=2)'))","HTTPConnectionPool(host='www.just.ro', port=80): Read timed out. (read timeout=2)"
justice.bg,"HTTPSConnectionPool(host='justice.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='justice.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
justice.gov.il,"HTTPSConnectionPool(host='justice.gov.il', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.justice.gov.il', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
jw.org,"HTTPSConnectionPool(host='www.jw.org', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.jw.org', port=443): Read timed out. (read timeout=2)"
kaldata.com,"HTTPSConnectionPool(host='www.kaldata.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.kaldata.com', port=443): Read timed out. (read timeout=2)"
kalkulatorkalorii.net,"HTTPSConnectionPool(host='kalkulatorkalorii.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='kalkulatorkalorii.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
kam.si,"HTTPSConnectionPool(host='kam.si', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='kam.si', port=80): Read timed out. (read timeout=2)"
kamsdetmi.sk,"HTTPSConnectionPool(host='kamsdetmi.sk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)')))","HTTPConnectionPool(host='kamsdetmi.sk', port=80): Read timed out. (read timeout=2)"
kaposvarmost.hu,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
kapruka.com,"HTTPSConnectionPool(host='kapruka.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='kapruka.com', port=443): Read timed out. (read timeout=2)"
kar.nic.in,"HTTPSConnectionPool(host='kar.nic.in', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f830da6d8b0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='kar.nic.in', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8309ffb520>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
karabuk.edu.tr,"HTTPSConnectionPool(host='karabuk.edu.tr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8306eecb80>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='karabuk.edu.tr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f830c18e790>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
karpol.lt,"HTTPSConnectionPool(host='www.karpol.lt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.karpol.lt', port=443): Read timed out. (read timeout=2)"
kathimerini.com.cy,"HTTPSConnectionPool(host='kathimerini.com.cy', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='kathimerini.com.cy', port=80): Read timed out. (read timeout=2)"
kaunoklinikos.lt,"HTTPSConnectionPool(host='kaunoklinikos.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPConnectionPool(host='kaunoklinikos.lt', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f830cb139d0>, 'Connection to kaunoklinikos.lt timed out. (connect timeout=2)'))"
kbc-zagreb.hr,"HTTPSConnectionPool(host='kbc-zagreb.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f830c306df0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='kbc-zagreb.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f83068e5160>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
kcb.vn,"HTTPSConnectionPool(host='kcb.vn', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='kcb.vn', port=80): Read timed out. (read timeout=2)"
