irishstatutebook.ie,"HTTPSConnectionPool(host='irishstatutebook.ie', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9dfea9d580>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='irishstatutebook.ie', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9dfe3a0520>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
irisplaza.co.jp,"HTTPSConnectionPool(host='irisplaza.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9dfe91db50>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='irisplaza.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9dfe19b4f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
isa.gov.il,"HTTPSConnectionPool(host='isa.gov.il', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9dfe61cf40>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='isa.gov.il', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9dfd8dac40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
isi.ac.id,"HTTPSConnectionPool(host='isi.ac.id', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='isi.ac.id', port=80): Read timed out. (read timeout=2)"
iskra.bg,"HTTPSConnectionPool(host='www.iskra.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.iskra.bg', port=443): Read timed out. (read timeout=2)"
iss.it,"HTTPSConnectionPool(host='iss.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9dfb65c220>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='iss.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9dfbf20af0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
istanbulc.edu.tr,"HTTPSConnectionPool(host='istanbulc.edu.tr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='istanbulc.edu.tr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
istanbulkitapcisi.com,"HTTPSConnectionPool(host='istanbulkitapcisi.com', port=443): Read timed out.","HTTPConnectionPool(host='istanbulkitapcisi.com', port=80): Read timed out. (read timeout=2)"
itau.com.uy,"HTTPSConnectionPool(host='itau.com.uy', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9dfa620610>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='itau.com.uy', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9dfd21f9a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
its-mo.com,"HTTPSConnectionPool(host='its-mo.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9df9c78670>: Failed to establish a new connection: [Errno 113] No route to host'))","HTTPConnectionPool(host='its-mo.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9dfaffed90>: Failed to establish a new connection: [Errno 113] No route to host'))"
itsvet.com,"HTTPSConnectionPool(host='itsvet.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='itsvet.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
itu.org.il,"HTTPSConnectionPool(host='itu.org.il', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='itu.org.il', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
iu.edu.jo,"HTTPSConnectionPool(host='iu.edu.jo', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='iu.edu.jo', port=443): Read timed out. (read timeout=2)"
ivd.ru,"HTTPSConnectionPool(host='www.ivd.ru', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.ivd.ru', port=443): Read timed out. (read timeout=2)"
ivivu.com,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
ivote.co.za,"HTTPSConnectionPool(host='ivote.co.za', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.ivote.co.za', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
iyifirma.com,"HTTPSConnectionPool(host='iyifirma.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9dfc25dd90>, 'Connection to iyifirma.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='iyifirma.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9df98f7fd0>, 'Connection to iyifirma.com timed out. (connect timeout=2)'))"
jabarprov.go.id,"HTTPSConnectionPool(host='jabarprov.go.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='jabarprov.go.id', port=443): Read timed out. (read timeout=2)"
jadrolinija.hr,"HTTPSConnectionPool(host='jadrolinija.hr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9dfbe52b80>, 'Connection to jadrolinija.hr timed out. (connect timeout=2)'))","HTTPConnectionPool(host='jadrolinija.hr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9dfe785fa0>, 'Connection to jadrolinija.hr timed out. (connect timeout=2)'))"
jaf.mil.jo,"HTTPSConnectionPool(host='jaf.mil.jo', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='jaf.mil.jo', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
janisroze.lv,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
japanpost.jp,"HTTPSConnectionPool(host='japanpost.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9dfd2f8130>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='japanpost.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9df8f259d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
javerianacali.edu.co,"HTTPSConnectionPool(host='javerianacali.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9dfc5f11f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='javerianacali.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9df8237be0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
jawharati.ma,"HTTPSConnectionPool(host='jawharati.ma', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'jawharati.ma' doesn't match either of '*.web-hosting.com', 'web-hosting.com'"")))","HTTPConnectionPool(host='jawharati.ma', port=80): Read timed out. (read timeout=2)"
jdnet.gr.jp,"HTTPSConnectionPool(host='jdnet.gr.jp', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9dfb501850>, 'Connection to jdnet.gr.jp timed out. (connect timeout=2)'))","HTTPConnectionPool(host='jdnet.gr.jp', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9dfb9212e0>, 'Connection to jdnet.gr.jp timed out. (connect timeout=2)'))"
jeddah.gov.sa,"HTTPSConnectionPool(host='jeddah.gov.sa', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9df7f2d4c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='jeddah.gov.sa', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9dfc80e8e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
jenite.bg,"HTTPSConnectionPool(host='jenite.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='jenite.bg', port=443): Read timed out. (read timeout=2)"
jetro.go.jp,"HTTPSConnectionPool(host='jetro.go.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9dfd5e6ca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='jetro.go.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9df93aa100>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
jgypk.hu,"HTTPSConnectionPool(host='jgypk.hu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'jgypk.hu' doesn't match either of '*.mediacenter.hu', 'mediacenter.hu'"")))",Exceeded 30 redirects.
jica.go.jp,"HTTPSConnectionPool(host='jica.go.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9dfb7b8a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='jica.go.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9df64fcc70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
jimhorsfield.com,"HTTPSConnectionPool(host='jimhorsfield.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9dfb9a3430>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='jimhorsfield.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9df7f03d30>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
jma.go.jp,"HTTPSConnectionPool(host='jma.go.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9dfc3384c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='jma.go.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9df6870b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
jobinfo.hu,"HTTPSConnectionPool(host='jobinfo.hu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'jobinfo.hu' doesn't match 'www.jobinfo.hu'"")))","HTTPSConnectionPool(host='www.jobinfo.hu', port=443): Read timed out. (read timeout=2)"
jobkarov.com,"HTTPSConnectionPool(host='jobkarov.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='jobkarov.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9dfb21dc40>, 'Connection to jobkarov.com timed out. (connect timeout=2)'))"
jobscentral.com.sg,"HTTPSConnectionPool(host='jobscentral.com.sg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='jobscentral.com.sg', port=443): Read timed out. (read timeout=2)"
jobsite.co.uk,"HTTPSConnectionPool(host='www.jobsite.co.uk', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.jobsite.co.uk', port=80): Read timed out. (read timeout=2)"
jobtopgun.com,"HTTPSConnectionPool(host='jobtopgun.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.jobtopgun.com', port=443): Read timed out. (read timeout=2)"
jobzaty.com,"HTTPSConnectionPool(host='www.jobzaty.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.jobzaty.com', port=443): Read timed out. (read timeout=2)"
jornaldeangola.ao,"HTTPSConnectionPool(host='jornaldeangola.ao', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='jornaldeangola.ao', port=80): Read timed out. (read timeout=2)"
joshinweb.jp,"HTTPSConnectionPool(host='joshinweb.jp', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='joshinweb.jp', port=80): Read timed out. (read timeout=2)"
journaldequebec.com,"HTTPSConnectionPool(host='www.journaldequebec.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.journaldequebec.com', port=443): Read timed out. (read timeout=2)"
joy.ne.jp,"HTTPSConnectionPool(host='joy.ne.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9dfdf2c760>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='joy.ne.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9dfc0a3f40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
jpa.gov.my,"HTTPSConnectionPool(host='jpa.gov.my', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9dfa590370>, 'Connection to jpa.gov.my timed out. (connect timeout=2)'))","HTTPConnectionPool(host='jpa.gov.my', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9df82a84f0>, 'Connection to jpa.gov.my timed out. (connect timeout=2)'))"
jpn.org,"HTTPSConnectionPool(host='jpn.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9dfcccda30>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='jpn.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9df7dd0940>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
jr-odekake.net,"HTTPSConnectionPool(host='jr-odekake.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9dfcf4d190>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='jr-odekake.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9df705aaf0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
jreast.co.jp,"HTTPSConnectionPool(host='jreast.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9df6d404c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='jreast.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9df8240370>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
js88.com,"HTTPSConnectionPool(host='js88.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9dfd243610>, 'Connection to js88.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='js88.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9dfcfc13d0>, 'Connection to js88.com timed out. (connect timeout=2)'))"
jst.go.jp,"HTTPSConnectionPool(host='jst.go.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9df9459a00>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='jst.go.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9df928d0a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
jtb.co.jp,"HTTPSConnectionPool(host='www.jtb.co.jp', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.jtb.co.jp', port=80): Read timed out. (read timeout=2)"
jtconsulting.be,"HTTPSConnectionPool(host='jtconsulting.be', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9df4cd2130>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='jtconsulting.be', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9df4ed87c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
juduo.cc,"HTTPSConnectionPool(host='juduo.cc', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.juduo.cc', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
jujuy.gob.ar,"HTTPSConnectionPool(host='jujuy.gob.ar', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1124)')))","HTTPConnectionPool(host='jujuy.gob.ar', port=80): Read timed out. (read timeout=2)"
jumsinfo.lt,"HTTPSConnectionPool(host='jumsinfo.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1124)')))","HTTPConnectionPool(host='www.jumsinfo.lt', port=80): Read timed out. (read timeout=2)"
juniorsoccer-news.com,"HTTPSConnectionPool(host='www.juniorsoccer-news.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.juniorsoccer-news.com', port=443): Read timed out. (read timeout=2)"
jurbarkosviesa.lt,"HTTPSConnectionPool(host='jurbarkosviesa.lt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='jurbarkosviesa.lt', port=443): Read timed out. (read timeout=2)"
juridicas.com,"HTTPSConnectionPool(host='juridicas.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'juridicas.com' doesn't match either of 'noticias.juridicas.com', 'www.noticias.juridicas.com'"")))","HTTPSConnectionPool(host='juridicas.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'juridicas.com' doesn't match either of 'noticias.juridicas.com', 'www.noticias.juridicas.com'"")))"
jurisprudencia.gob.sv,"HTTPSConnectionPool(host='jurisprudencia.gob.sv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9dfc419f70>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='jurisprudencia.gob.sv', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9df5306cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
juritravail.com,"HTTPSConnectionPool(host='www.juritravail.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.juritravail.com', port=443): Read timed out. (read timeout=2)"
just.ro,"HTTPSConnectionPool(host='just.ro', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9dfd0acb50>, 'Connection to just.ro timed out. (connect timeout=2)'))","HTTPConnectionPool(host='www.just.ro', port=80): Read timed out. (read timeout=2)"
justacote.com,"HTTPSConnectionPool(host='www.justacote.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.justacote.com', port=443): Read timed out. (read timeout=2)"
justice.bg,"HTTPSConnectionPool(host='justice.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='justice.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
justice.gov.il,"HTTPSConnectionPool(host='justice.gov.il', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.justice.gov.il', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
jw.org,"HTTPSConnectionPool(host='www.jw.org', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.jw.org', port=443): Read timed out. (read timeout=2)"
kaikkisyovasta.fi,"HTTPSConnectionPool(host='kaikkisyovasta.fi', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.kaikkisyovasta.fi', port=443): Read timed out. (read timeout=2)"
kalkulatorkalorii.net,"HTTPSConnectionPool(host='kalkulatorkalorii.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='kalkulatorkalorii.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
kamsdetmi.sk,"HTTPSConnectionPool(host='kamsdetmi.sk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1124)')))","HTTPConnectionPool(host='kamsdetmi.sk', port=80): Read timed out. (read timeout=2)"
kaposvarmost.hu,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
kar.nic.in,"HTTPSConnectionPool(host='kar.nic.in', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9dfe203370>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='kar.nic.in', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9df495d940>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
karabuk.edu.tr,"HTTPSConnectionPool(host='karabuk.edu.tr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9dfa849e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='karabuk.edu.tr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9df6698be0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
karpol.lt,"HTTPSConnectionPool(host='www.karpol.lt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.karpol.lt', port=443): Read timed out. (read timeout=2)"
kassir.ru,"HTTPSConnectionPool(host='kassir.ru', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9df64fc430>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPSConnectionPool(host='kassir.ru', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9dfe40d790>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
kaunoklinikos.lt,"HTTPSConnectionPool(host='kaunoklinikos.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPConnectionPool(host='kaunoklinikos.lt', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9df96eb7f0>, 'Connection to kaunoklinikos.lt timed out. (connect timeout=2)'))"
kbc-rijeka.hr,"HTTPSConnectionPool(host='kbc-rijeka.hr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'kbc-rijeka.hr' doesn't match either of '*.croadria.com', 'croadria.com'"")))","HTTPConnectionPool(host='kbc-rijeka.hr', port=80): Read timed out. (read timeout=2)"
kbc-zagreb.hr,"HTTPSConnectionPool(host='kbc-zagreb.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9df4852220>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='kbc-zagreb.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9df8db3d00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
kcb.vn,"HTTPSConnectionPool(host='kcb.vn', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='kcb.vn', port=80): Read timed out. (read timeout=2)"
