locatelcolombia.com,"HTTPSConnectionPool(host='locatelcolombia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4437f4c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='locatelcolombia.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4437614c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
logicrdv.fr,"HTTPSConnectionPool(host='logicrdv.fr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.logicrdv.fr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
loislandgraf.us,"HTTPSConnectionPool(host='loislandgraf.us', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='loislandgraf.us', port=80): Read timed out. (read timeout=2)"
lombardiabeniculturali.it,"HTTPSConnectionPool(host='lombardiabeniculturali.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'lombardiabeniculturali.it' doesn't match either of 'lispa.it', 'www.lispa.it'"")))","HTTPConnectionPool(host='lombardiabeniculturali.it', port=80): Read timed out. (read timeout=2)"
longdom.org,"HTTPSConnectionPool(host='www.longdom.org', port=443): Read timed out.","HTTPSConnectionPool(host='www.longdom.org', port=443): Read timed out."
looduspere.ee,"HTTPSConnectionPool(host='www.looduspere.ee', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.looduspere.ee', port=443): Read timed out. (read timeout=2)"
loopnet.com,"HTTPSConnectionPool(host='loopnet.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='loopnet.com', port=80): Read timed out. (read timeout=2)"
lossc.co,"HTTPSConnectionPool(host='lossc.co', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='lossc.co', port=80): Read timed out. (read timeout=2)"
lowes.ca,"HTTPSConnectionPool(host='www.lowes.ca', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.lowes.ca', port=443): Read timed out. (read timeout=2)"
lowes.com,"HTTPSConnectionPool(host='www.lowes.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.lowes.com', port=443): Read timed out. (read timeout=2)"
lsmu.lt,"HTTPSConnectionPool(host='lsmu.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='lsmuni.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
lsmuni.lt,"HTTPSConnectionPool(host='lsmuni.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='lsmuni.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
lsu.lt,"HTTPSConnectionPool(host='lsu.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'lsu.lt' doesn't match either of 'www.lsu.lt', 'journals.lsu.lt'"")))","HTTPSConnectionPool(host='www.lsu.lt', port=443): Read timed out. (read timeout=2)"
lt10digital.com.ar,"HTTPSConnectionPool(host='www.lt10digital.com.ar', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.lt10digital.com.ar', port=443): Read timed out. (read timeout=2)"
luiss.it,"HTTPSConnectionPool(host='luiss.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4431e19a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='luiss.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa43ef26220>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
lukoprekyba.lt,"HTTPSConnectionPool(host='www.lukoprekyba.lt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.lukoprekyba.lt', port=443): Read timed out. (read timeout=2)"
lums.edu.pk,"HTTPSConnectionPool(host='lums.edu.pk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='lums.edu.pk', port=443): Read timed out. (read timeout=2)"
lunchtime.co.nz,"HTTPSConnectionPool(host='lunchtime.co.nz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='lunchtime.co.nz', port=443): Read timed out. (read timeout=2)"
lusiadas.pt,"HTTPSConnectionPool(host='lusiadas.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa44142d8e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='lusiadas.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa43dce3a30>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
luts.ee,"HTTPSConnectionPool(host='luts.ee', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa43d44bbb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='luts.ee', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa43fb709d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
lyricsbox.com,"HTTPSConnectionPool(host='lyricsbox.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa43cfab1c0>, 'Connection to lyricsbox.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='lyricsbox.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa440bb6c10>, 'Connection to lyricsbox.com timed out. (connect timeout=2)'))"
lzs.lt,"HTTPSConnectionPool(host='lzs.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'lzs.lt' doesn't match either of '*.balt.net', 'balt.net'"")))","HTTPConnectionPool(host='lzs.lt', port=80): Read timed out. (read timeout=2)"
m-almada.pt,"HTTPSConnectionPool(host='m-almada.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa43c552850>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='m-almada.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa43d09eee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
macmillandictionary.com,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
macmillanthesaurus.com,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
madamefigaro.gr,"HTTPSConnectionPool(host='www.madamefigaro.gr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.madamefigaro.gr', port=443): Read timed out. (read timeout=2)"
madeingreece.news,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
madrid.org,"HTTPSConnectionPool(host='madrid.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4422e5af0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='madrid.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4430ac910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
maedchenflohmarkt.de,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
maff.go.jp,"HTTPSConnectionPool(host='maff.go.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa439e9e580>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='maff.go.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa44247b9a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
magaseek.com,"HTTPSConnectionPool(host='magaseek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa439e9e490>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='magaseek.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa442dea1f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
magazinauto.com,"HTTPSConnectionPool(host='www.magazinauto.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.magazinauto.com', port=443): Read timed out. (read timeout=2)"
magicnobilje.com,"HTTPSConnectionPool(host='www.magicnobilje.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.magicnobilje.com', port=443): Read timed out. (read timeout=2)"
magyarkozlony.hu,"HTTPSConnectionPool(host='magyarkozlony.hu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='magyarkozlony.hu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
mahidol.ac.th,"HTTPSConnectionPool(host='mahidol.ac.th', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='mahidol.ac.th', port=443): Read timed out. (read timeout=2)"
mai.gov.pt,"HTTPSConnectionPool(host='mai.gov.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4425f27f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mai.gov.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa443358c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
mainstand.co.th,"HTTPSConnectionPool(host='mainstand.co.th', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='mainstand.co.th', port=443): Read timed out. (read timeout=2)"
maisbolsas.com.br,"HTTPSConnectionPool(host='maisbolsas.com.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='maisbolsas.com.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
maisribatejo.pt,"HTTPSConnectionPool(host='maisribatejo.pt', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='maisribatejo.pt', port=80): Read timed out. (read timeout=2)"
makemytrip.com,"HTTPSConnectionPool(host='makemytrip.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa443679c40>, 'Connection to makemytrip.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='makemytrip.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa4402fab50>, 'Connection to makemytrip.com timed out. (connect timeout=2)'))"
makeuseof.com,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
malizakladi.si,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
mam-e.it,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","HTTPConnectionPool(host='mam-e.it', port=80): Read timed out. (read timeout=2)"
mamagirl.jp,"HTTPSConnectionPool(host='mamagirl.jp', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='mamagirl.jp', port=443): Read timed out. (read timeout=2)"
man-trailer.com,"HTTPSConnectionPool(host='man-trailer.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='man-trailer.com', port=443): Read timed out. (read timeout=2)"
manalonline.com,"HTTPSConnectionPool(host='manalonline.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'manalonline.com' doesn't match 'www.manalonline.com'"")))","HTTPConnectionPool(host='manalonline.com', port=80): Read timed out. (read timeout=2)"
mandmdirect.ie,"HTTPSConnectionPool(host='mandmdirect.ie', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'mandmdirect.ie' doesn't match either of 'www.mandmdirect.com', 'mandmdirect.com', 'email.mandmdirect.com', 'www.mandmdirect.ie', 'euro.mandmdirect.com', 'mmgw.mmis-p.com', 'resources.mandmdirect.com', 'wwwm.mandmdirect.com', 'services.mandmdirect.com', 'www.mandmdirect.pl', 'www.mandmdirect.dk', 'www.mandmdirect.fr', 'www.mandmdirect.de', 'unsub.email.mandmdirect.com', 'gateway.mandmdirect.com', 'www.mandmdirect.nl', 'www.mandmdirect.at', 'edocs.mandmdirect.com', 'scripts.mandmdirect.com'"")))","HTTPConnectionPool(host='www.mandmdirect.ie', port=80): Read timed out. (read timeout=2)"
mangozero.com,"HTTPSConnectionPool(host='www.mangozero.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.mangozero.com', port=443): Read timed out. (read timeout=2)"
mapanicaragua.com,"HTTPSConnectionPool(host='mapanicaragua.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa43a51a6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mapanicaragua.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa439b9aa00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
mapexpress.ma,"HTTPSConnectionPool(host='mapexpress.ma', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPConnectionPool(host='www.mapexpress.ma', port=80): Read timed out. (read timeout=2)"
maranatha.edu,"HTTPSConnectionPool(host='www.maranatha.edu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.maranatha.edu', port=443): Read timed out. (read timeout=2)"
marcatucuman.com.ar,"HTTPSConnectionPool(host='marcatucuman.com.ar', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa43f942a30>, 'Connection to marcatucuman.com.ar timed out. (connect timeout=2)'))","HTTPConnectionPool(host='marcatucuman.com.ar', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa4409eafa0>, 'Connection to marcatucuman.com.ar timed out. (connect timeout=2)'))"
marianives.it,"HTTPSConnectionPool(host='www.marianives.it', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.marianives.it', port=443): Read timed out. (read timeout=2)"
marijampole.lt,"HTTPSConnectionPool(host='marijampole.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='marijampole.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
marionnaud.fr,"HTTPSConnectionPool(host='marionnaud.fr', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='marionnaud.fr', port=80): Read timed out. (read timeout=2)"
marn.gob.sv,"HTTPSConnectionPool(host='marn.gob.sv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa441890d60>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='marn.gob.sv', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa44030d9a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
marquartogsoby.dk,"HTTPSConnectionPool(host='marquartogsoby.dk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa44330f2b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='marquartogsoby.dk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa439ab1b20>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
marumura.com,"HTTPSConnectionPool(host='marumura.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.marumura.com', port=443): Read timed out. (read timeout=2)"
mas.gov.sg,"HTTPSConnectionPool(host='mas.gov.sg', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa43cfaad60>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mas.gov.sg', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4415c8a00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
mascus.lv,"HTTPSConnectionPool(host='mascus.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.mascus.lv', port=443): Read timed out. (read timeout=2)"
maskinbladet.dk,"HTTPSConnectionPool(host='www.maskinbladet.dk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.maskinbladet.dk', port=443): Read timed out. (read timeout=2)"
maskinisten.net,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
mat3am.net,"HTTPSConnectionPool(host='www.mat3am.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.mat3am.net', port=443): Read timed out. (read timeout=2)"
matb3aa.com,"HTTPSConnectionPool(host='www.matb3aa.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.matb3aa.com', port=443): Read timed out. (read timeout=2)"
matica.hr,"HTTPSConnectionPool(host='matica.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa439ae14f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='matica.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa43a29bb20>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
matoppskrift.no,"HTTPSConnectionPool(host='www.matoppskrift.no', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.matoppskrift.no', port=443): Read timed out. (read timeout=2)"
mazeikiai.lt,"HTTPSConnectionPool(host='mazeikiai.lt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa44125afd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mazeikiai.lt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa442e6af10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
mch.cl,"HTTPSConnectionPool(host='mch.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa439940a30>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mch.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa442a393a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
mcu.es,"HTTPSConnectionPool(host='mcu.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa440a3ab50>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mcu.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa442b4a310>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
mcw.gov.cy,"HTTPSConnectionPool(host='mcw.gov.cy', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4403e6490>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mcw.gov.cy', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa43d07e4c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
mdp.edu.ar,"HTTPSConnectionPool(host='mdp.edu.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa43b19f310>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mdp.edu.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa43cdc36a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
me.gov.ar,"HTTPSConnectionPool(host='me.gov.ar', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'me.gov.ar' doesn't match either of '*.argentina.gob.ar', 'argentina.gob.ar'"")))","HTTPConnectionPool(host='me.gov.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4416d3850>: Failed to establish a new connection: [Errno 111] Connection refused'))"
meb.k12.tr,"HTTPSConnectionPool(host='meb.k12.tr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4416726d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='meb.k12.tr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa442a1c790>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
mec.es,"HTTPSConnectionPool(host='mec.es', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1124)')))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
mec.pt,"HTTPSConnectionPool(host='mec.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa442da8a00>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mec.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4409c0940>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
mecha.cc,"HTTPSConnectionPool(host='mecha.cc', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa441c2dee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mecha.cc', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa439b5b940>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
