loga.vn,"HTTPSConnectionPool(host='loga.vn', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='loga.vn', port=80): Read timed out. (read timeout=2)"
logicrdv.fr,"HTTPSConnectionPool(host='logicrdv.fr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.logicrdv.fr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
loja.gob.ec,"HTTPSConnectionPool(host='loja.gob.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.loja.gob.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
lombardiabeniculturali.it,"HTTPSConnectionPool(host='www.lombardiabeniculturali.it', port=443): Read timed out.","HTTPSConnectionPool(host='www.lombardiabeniculturali.it', port=443): Read timed out. (read timeout=2)"
lonestarinspectioncompany.com,"HTTPSConnectionPool(host='lonestarinspectioncompany.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c4a2ecd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='lonestarinspectioncompany.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c4b18130>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
looduspere.ee,"HTTPSConnectionPool(host='www.looduspere.ee', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.looduspere.ee', port=443): Read timed out. (read timeout=2)"
lookup.pk,"HTTPSConnectionPool(host='lookup.pk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.lookup.pk', port=443): Read timed out. (read timeout=2)"
loopnet.com,"HTTPSConnectionPool(host='loopnet.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='loopnet.com', port=80): Read timed out. (read timeout=2)"
lorientlejour.com,"HTTPSConnectionPool(host='www.lorientlejour.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.lorientlejour.com', port=443): Read timed out. (read timeout=2)"
lowes.ca,"HTTPSConnectionPool(host='www.lowes.ca', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.lowes.ca', port=443): Read timed out. (read timeout=2)"
lowes.com,"HTTPSConnectionPool(host='www.lowes.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.lowes.com', port=443): Read timed out. (read timeout=2)"
lsmu.lt,"HTTPSConnectionPool(host='lsmu.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='lsmuni.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
lsmuni.lt,"HTTPSConnectionPool(host='lsmuni.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='lsmuni.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
luattrongtay.vn,"HTTPSConnectionPool(host='luattrongtay.vn', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='luattrongtay.vn', port=443): Read timed out. (read timeout=2)"
luc-gilis.be,"HTTPSConnectionPool(host='luc-gilis.be', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.luc-gilis.be', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1124)')))"
luiss.it,"HTTPSConnectionPool(host='luiss.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c4976d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='luiss.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c48af880>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
lums.edu.pk,"HTTPSConnectionPool(host='lums.edu.pk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='lums.edu.pk', port=443): Read timed out. (read timeout=2)"
lunchtime.co.nz,"HTTPSConnectionPool(host='lunchtime.co.nz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='lunchtime.co.nz', port=443): Read timed out. (read timeout=2)"
lundeborgbnb.dk,"HTTPSConnectionPool(host='lundeborgbnb.dk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c4a66160>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='lundeborgbnb.dk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c4990670>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
lusiadas.pt,"HTTPSConnectionPool(host='lusiadas.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c4b18e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='lusiadas.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c4a39f70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
lutrija.hr,"HTTPSConnectionPool(host='lutrija.hr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'lutrija.hr' doesn't match 'www.lutrija.hr'"")))","HTTPSConnectionPool(host='lutrija.hr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'lutrija.hr' doesn't match 'www.lutrija.hr'"")))"
luts.ee,"HTTPSConnectionPool(host='luts.ee', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c47e4af0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='luts.ee', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c49906d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
luxurycarrentalitaly.it,Exceeded 30 redirects.,Exceeded 30 redirects.
lzs.lt,"HTTPSConnectionPool(host='lzs.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'lzs.lt' doesn't match either of '*.balt.net', 'balt.net'"")))","HTTPConnectionPool(host='lzs.lt', port=80): Read timed out. (read timeout=2)"
m-almada.pt,"HTTPSConnectionPool(host='m-almada.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c40d6880>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='m-almada.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c40d6760>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
m-culture.go.th,"HTTPSConnectionPool(host='m-culture.go.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c481e850>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='m-culture.go.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c4807a00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
machimachi.com,"HTTPSConnectionPool(host='machimachi.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='machimachi.com', port=443): Read timed out. (read timeout=2)"
macmillandictionary.com,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
macmillanthesaurus.com,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
macrumors.com,"HTTPSConnectionPool(host='macrumors.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='macrumors.com', port=443): Read timed out. (read timeout=2)"
macys.com,Exceeded 30 redirects.,Exceeded 30 redirects.
madeingreece.news,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
madrid.org,"HTTPSConnectionPool(host='madrid.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c3927490>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='madrid.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c38edd60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
maduniverset.dk,"HTTPSConnectionPool(host='www.maduniverset.dk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.maduniverset.dk', port=443): Read timed out. (read timeout=2)"
maedchenflohmarkt.de,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
maff.go.jp,"HTTPSConnectionPool(host='maff.go.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c3f5a9a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='maff.go.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c3058040>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
maga.gob.gt,"HTTPSConnectionPool(host='maga.gob.gt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'maga.gob.gt' doesn't match '*.maga.gob.gt'"")))","HTTPConnectionPool(host='maga.gob.gt', port=80): Read timed out. (read timeout=2)"
magaseek.com,"HTTPSConnectionPool(host='magaseek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c3086100>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='magaseek.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c48cc310>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
magazinauto.com,"HTTPSConnectionPool(host='www.magazinauto.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.magazinauto.com', port=443): Read timed out. (read timeout=2)"
magro.hu,"HTTPSConnectionPool(host='www.magro.hu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.magro.hu', port=443): Read timed out. (read timeout=2)"
magyarkozlony.hu,"HTTPSConnectionPool(host='magyarkozlony.hu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='magyarkozlony.hu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
mahidol.ac.th,"HTTPSConnectionPool(host='mahidol.ac.th', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='mahidol.ac.th', port=443): Read timed out. (read timeout=2)"
mai.gov.pt,"HTTPSConnectionPool(host='mai.gov.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c3094880>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mai.gov.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c3dff190>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
mainstand.co.th,"HTTPSConnectionPool(host='mainstand.co.th', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='mainstand.co.th', port=443): Read timed out. (read timeout=2)"
mainyk.lt,"HTTPSConnectionPool(host='mainyk.lt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c4aa2730>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='www.mainyk.lt', port=80): Read timed out. (read timeout=2)"
maisbolsas.com.br,"HTTPSConnectionPool(host='maisbolsas.com.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='maisbolsas.com.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
makemytrip.com,"HTTPSConnectionPool(host='www.makemytrip.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.makemytrip.com', port=443): Read timed out. (read timeout=2)"
makeuseof.com,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
malizakladi.si,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
mamaplus.md,"HTTPSConnectionPool(host='mamaplus.md', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.mamaplus.md', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff9c3955850>, 'Connection to www.mamaplus.md timed out. (connect timeout=2)'))"
man-trailer.com,"HTTPSConnectionPool(host='man-trailer.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='man-trailer.com', port=443): Read timed out. (read timeout=2)"
mandmdirect.ie,"HTTPSConnectionPool(host='mandmdirect.ie', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'mandmdirect.ie' doesn't match either of 'www.mandmdirect.com', 'mandmdirect.com', 'email.mandmdirect.com', 'www.mandmdirect.ie', 'euro.mandmdirect.com', 'mmgw.mmis-p.com', 'resources.mandmdirect.com', 'wwwm.mandmdirect.com', 'services.mandmdirect.com', 'www.mandmdirect.pl', 'www.mandmdirect.dk', 'www.mandmdirect.fr', 'www.mandmdirect.de', 'unsub.email.mandmdirect.com', 'gateway.mandmdirect.com', 'www.mandmdirect.nl', 'www.mandmdirect.at', 'edocs.mandmdirect.com', 'scripts.mandmdirect.com'"")))","HTTPConnectionPool(host='www.mandmdirect.ie', port=80): Read timed out. (read timeout=2)"
mapanicaragua.com,"HTTPSConnectionPool(host='mapanicaragua.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c4b23d60>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mapanicaragua.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c2efe640>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
mapexpress.ma,"HTTPSConnectionPool(host='mapexpress.ma', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'mapexpress.ma' doesn't match either of 'maghreb1.ma', 'mapfinance.ma', 'mapparite.ma', 'mapsport.ma', 'maptourisme.ma', 'nwl.faapa.info', 'www.maghreb1.ma', 'www.mapfinance.ma', 'www.mapparite.ma', 'www.mapsport.ma', 'www.maptourisme.ma'"")))","HTTPConnectionPool(host='www.mapexpress.ma', port=80): Read timed out. (read timeout=2)"
mappaustria.com,"HTTPSConnectionPool(host='mappaustria.com', port=443): Read timed out.","HTTPSConnectionPool(host='mappaustria.com', port=443): Read timed out. (read timeout=2)"
marcatucuman.com.ar,"HTTPSConnectionPool(host='marcatucuman.com.ar', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff9c48076a0>, 'Connection to marcatucuman.com.ar timed out. (connect timeout=2)'))","HTTPConnectionPool(host='marcatucuman.com.ar', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff9c3017250>, 'Connection to marcatucuman.com.ar timed out. (connect timeout=2)'))"
marianives.it,"HTTPSConnectionPool(host='www.marianives.it', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.marianives.it', port=443): Read timed out. (read timeout=2)"
marijampole.lt,"HTTPSConnectionPool(host='marijampole.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='marijampole.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
marionnaud.fr,"HTTPSConnectionPool(host='marionnaud.fr', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='marionnaud.fr', port=80): Read timed out. (read timeout=2)"
marktjagd.de,"HTTPSConnectionPool(host='www.marktjagd.de', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.marktjagd.de', port=443): Read timed out. (read timeout=2)"
marn.gob.sv,"HTTPSConnectionPool(host='marn.gob.sv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c2fca340>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='marn.gob.sv', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c47bddf0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
marocannonces.com,"HTTPSConnectionPool(host='www.marocannonces.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.marocannonces.com', port=443): Read timed out. (read timeout=2)"
mas.gov.sg,"HTTPSConnectionPool(host='mas.gov.sg', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c390f760>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mas.gov.sg', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c2f832e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
mascus.lt,"HTTPSConnectionPool(host='mascus.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPConnectionPool(host='mascus.lt', port=80): Read timed out. (read timeout=2)"
maskinisten.net,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
mat3am.net,"HTTPSConnectionPool(host='www.mat3am.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.mat3am.net', port=443): Read timed out. (read timeout=2)"
matica.hr,"HTTPSConnectionPool(host='matica.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c4b3cf40>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='matica.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c3fcd910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
matkapuhelinfoorumi.fi,"HTTPSConnectionPool(host='matkapuhelinfoorumi.fi', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c3def520>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='matkapuhelinfoorumi.fi', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c398dd00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
matoppskrift.no,"HTTPSConnectionPool(host='www.matoppskrift.no', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.matoppskrift.no', port=443): Read timed out. (read timeout=2)"
maxmiraclemethod.info,"HTTPSConnectionPool(host='maxmiraclemethod.info', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c2fa2d00>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='maxmiraclemethod.info', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c3abda00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
mazeikiai.lt,"HTTPSConnectionPool(host='mazeikiai.lt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c3e33d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mazeikiai.lt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c3e55a30>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
mch.cl,"HTTPSConnectionPool(host='mch.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c2f2d0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mch.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c2f75fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
mcu.es,"HTTPSConnectionPool(host='mcu.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c49f7310>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mcu.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c4812040>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
mcw.gov.cy,"HTTPSConnectionPool(host='mcw.gov.cy', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c2f75ca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mcw.gov.cy', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c473b820>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
mdp.edu.ar,"HTTPSConnectionPool(host='mdp.edu.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c3a589d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mdp.edu.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c4159bb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
mdzol.com,"HTTPSConnectionPool(host='www.mdzol.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.mdzol.com', port=443): Read timed out. (read timeout=2)"
me.gov.ar,"HTTPSConnectionPool(host='me.gov.ar', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'me.gov.ar' doesn't match either of '*.argentina.gob.ar', 'argentina.gob.ar'"")))","HTTPConnectionPool(host='me.gov.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c4159580>: Failed to establish a new connection: [Errno 111] Connection refused'))"
meb.k12.tr,"HTTPSConnectionPool(host='meb.k12.tr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c40e2310>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='meb.k12.tr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c2905130>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
mec.es,"HTTPSConnectionPool(host='mec.es', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1124)')))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
mec.pt,"HTTPSConnectionPool(host='mec.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c4afca00>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mec.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c2787eb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
mecha.cc,"HTTPSConnectionPool(host='mecha.cc', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c4abfa60>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='mecha.cc', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9c4a5abe0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
