ocn.ne.jp,"HTTPSConnectionPool(host='www.ocn.ne.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.ocn.ne.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
odkazprestarostu.sk,"HTTPSConnectionPool(host='www.odkazprestarostu.sk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.odkazprestarostu.sk', port=443): Read timed out. (read timeout=2)"
oeffnungszeitenbuch.de,"HTTPSConnectionPool(host='oeffnungszeitenbuch.de', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2dd79af8b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='oeffnungszeitenbuch.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2dd78bf910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
oeticket.com,"HTTPSConnectionPool(host='oeticket.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2dd7b197c0>, 'Connection to oeticket.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='www.oeticket.com', port=80): Read timed out. (read timeout=2)"
offen.net,"HTTPSConnectionPool(host='offen.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.offen.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
officedepot.co.cr,"HTTPSConnectionPool(host='officedepot.co.cr', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='officedepot.co.cr', port=80): Read timed out. (read timeout=2)"
officedepot.com.sv,"HTTPSConnectionPool(host='officedepot.com.sv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2dd77f74f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='officedepot.com.sv', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2dd79524c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
offipalsta.com,"HTTPSConnectionPool(host='offipalsta.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='offipalsta.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
ofir.dk,"HTTPSConnectionPool(host='ofir.dk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2dd78183d0>: Failed to establish a new connection: [Errno 113] No route to host'))","HTTPConnectionPool(host='ofir.dk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2dd792ceb0>: Failed to establish a new connection: [Errno 113] No route to host'))"
ofppt.ma,"HTTPSConnectionPool(host='ofppt.ma', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2dd778fb50>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ofppt.ma', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2dd79207c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
oic.or.th,"HTTPSConnectionPool(host='oic.or.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2dd7756490>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='oic.or.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2dd76e86d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
oj.gob.gt,"HTTPSConnectionPool(host='oj.gob.gt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2dd76b6850>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='oj.gob.gt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2dd7762730>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
okanhastanesi.com.tr,"HTTPSConnectionPool(host='okanhastanesi.com.tr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='okanhastanesi.com.tr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
oleole.pl,"HTTPSConnectionPool(host='www.oleole.pl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.oleole.pl', port=443): Read timed out. (read timeout=2)"
olivemagazine.gr,"HTTPSConnectionPool(host='olivemagazine.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1124)')))","HTTPSConnectionPool(host='olivemagazine.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1124)')))"
olx.co.id,"HTTPSConnectionPool(host='olx.co.id', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2dd7616340>, 'Connection to olx.co.id timed out. (connect timeout=2)'))","HTTPConnectionPool(host='www.olx.co.id', port=80): Read timed out. (read timeout=2)"
olx.co.za,"HTTPSConnectionPool(host='olx.co.za', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2dd75e7fa0>, 'Connection to olx.co.za timed out. (connect timeout=2)'))","HTTPSConnectionPool(host='www.olx.co.za', port=443): Read timed out. (read timeout=2)"
olx.in,"HTTPSConnectionPool(host='olx.in', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2dd744ffd0>, 'Connection to olx.in timed out. (connect timeout=2)'))","HTTPConnectionPool(host='www.olx.in', port=80): Read timed out. (read timeout=2)"
omelhordobairro.com,"HTTPSConnectionPool(host='omelhordobairro.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.omelhordobairro.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
omfield.org,"HTTPSConnectionPool(host='omfield.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2dd78bfb80>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='omfield.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2dd74cc910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
omm.dk,"HTTPSConnectionPool(host='omm.dk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2dd77ab220>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='omm.dk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2dd76dbd00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
omni7.jp,"HTTPSConnectionPool(host='omni7.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2dd753fe80>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='omni7.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2dd7762dc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
omron.co.jp,"HTTPSConnectionPool(host='omron.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2dd7778880>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='omron.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2dd7969400>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
oncyprus.com,"HTTPSConnectionPool(host='www.oncyprus.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.oncyprus.com', port=443): Read timed out. (read timeout=2)"
onep.go.th,"HTTPSConnectionPool(host='onep.go.th', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2dd7465220>, 'Connection to onep.go.th timed out. (connect timeout=2)'))","HTTPConnectionPool(host='onep.go.th', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2dd73fd130>, 'Connection to onep.go.th timed out. (connect timeout=2)'))"
onepagefree.com,"HTTPSConnectionPool(host='onepagefree.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)')))","HTTPConnectionPool(host='onepagefree.com', port=80): Read timed out. (read timeout=2)"
onesearch.id,"HTTPSConnectionPool(host='onesearch.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='onesearch.id', port=443): Read timed out. (read timeout=2)"
onko-i.si,"HTTPSConnectionPool(host='onko-i.si', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2dd745a130>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='onko-i.si', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2dd75291c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
onlineexpo.com,"HTTPSConnectionPool(host='onlineexpo.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='onlineexpo.com', port=443): Read timed out. (read timeout=2)"
op-media.fi,"HTTPSConnectionPool(host='www.op-media.fi', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.op-media.fi', port=443): Read timed out. (read timeout=2)"
opais.co.ao,"HTTPSConnectionPool(host='opais.co.ao', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='opais.co.ao', port=443): Read timed out. (read timeout=2)"
opengov.gr,"HTTPSConnectionPool(host='opengov.gr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2dd78bf9a0>, 'Connection to opengov.gr timed out. (connect timeout=2)'))","HTTPConnectionPool(host='www.opengov.gr', port=80): Read timed out. (read timeout=2)"
openingsuren.info,"HTTPSConnectionPool(host='www.openingsuren.info', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.openingsuren.info', port=443): Read timed out. (read timeout=2)"
opentran.net,"HTTPSConnectionPool(host='opentran.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='opentran.net', port=443): Read timed out. (read timeout=2)"
opsmoac.go.th,"HTTPSConnectionPool(host='opsmoac.go.th', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2dd723c4c0>, 'Connection to opsmoac.go.th timed out. (connect timeout=2)'))","HTTPConnectionPool(host='opsmoac.go.th', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2dd7465fa0>, 'Connection to opsmoac.go.th timed out. (connect timeout=2)'))"
optus.com.au,"HTTPSConnectionPool(host='www.optus.com.au', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.optus.com.au', port=80): Read timed out. (read timeout=2)"
ordenjuridico.gob.mx,"HTTPSConnectionPool(host='ordenjuridico.gob.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2dd747c3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='ordenjuridico.gob.mx', port=80): Read timed out. (read timeout=2)"
ore.edu.pl,"HTTPSConnectionPool(host='ore.edu.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='ore.edu.pl', port=443): Max retries exceeded with url: // (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
organiseereentopevent.nl,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
orst.go.th,"HTTPSConnectionPool(host='orst.go.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2dd77b6670>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='orst.go.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2dd7774df0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
osaka-u.ac.jp,"HTTPSConnectionPool(host='osaka-u.ac.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2dd7413b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='osaka-u.ac.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2dd77418b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
osaka.lg.jp,"HTTPSConnectionPool(host='osaka.lg.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2dd7146ac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='osaka.lg.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2dd78273d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ose.com.uy,"HTTPSConnectionPool(host='ose.com.uy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)')))","HTTPConnectionPool(host='ose.com.uy', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2dd744f160>, 'Connection to ose.com.uy timed out. (connect timeout=2)'))"
osloskolen.no,"HTTPSConnectionPool(host='osloskolen.no', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2dd80c7fa0>, 'Connection to osloskolen.no timed out. (connect timeout=2)'))","HTTPConnectionPool(host='osloskolen.no', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2dd76b65e0>, 'Connection to osloskolen.no timed out. (connect timeout=2)'))"
othaimmarkets.com,"HTTPSConnectionPool(host='othaimmarkets.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.othaimmarkets.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
otpbanka.hr,"HTTPSConnectionPool(host='otpbanka.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2dd75e7b80>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='otpbanka.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2dd763f550>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ous-hf.no,"HTTPSConnectionPool(host='ous-hf.no', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2dd72fcb20>, 'Connection to ous-hf.no timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ous-hf.no', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2dd75a80d0>, 'Connection to ous-hf.no timed out. (connect timeout=2)'))"
outofstepwineco.com,"HTTPSConnectionPool(host='outofstepwineco.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2dd7021bb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='outofstepwineco.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2dd76f2910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
overclockers.ru,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
overstock.ca,"HTTPSConnectionPool(host='www.overstock.ca', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.overstock.ca', port=443): Read timed out. (read timeout=2)"
overstock.com,"HTTPSConnectionPool(host='www.overstock.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.overstock.com', port=443): Read timed out. (read timeout=2)"
owg.pl,"HTTPSConnectionPool(host='owg.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.owg.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
owlapps.net,"HTTPSConnectionPool(host='owlapps.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.owlapps.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
oxfordlearnersdictionaries.com,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
oxfordreference.com,"HTTPSConnectionPool(host='oxfordreference.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='oxfordreference.com', port=443): Read timed out. (read timeout=2)"
ozon.rs,"HTTPSConnectionPool(host='www.ozon.rs', port=443): Read timed out.","HTTPSConnectionPool(host='www.ozon.rs', port=443): Read timed out."
ozon.travel,"HTTPSConnectionPool(host='www.ozon.ru', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.ozon.ru', port=443): Read timed out. (read timeout=2)"
ozs.si,"HTTPSConnectionPool(host='ozs.si', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2dd7736610>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ozs.si', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2dd70bd700>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
p-world.co.jp,"HTTPSConnectionPool(host='p-world.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2dd70a13a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='p-world.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2dd79399a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
paesionline.it,"HTTPConnectionPool(host='www.paesionline.it', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.paesionline.it', port=80): Read timed out. (read timeout=2)"
painaidii.com,"HTTPSConnectionPool(host='painaidii.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPConnectionPool(host='www.painaidii.com', port=80): Read timed out. (read timeout=2)"
paintandpowerwashct.com,"HTTPSConnectionPool(host='paintandpowerwashct.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2dd75297c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='paintandpowerwashct.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2dd7485f70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pais.co.il,"HTTPSConnectionPool(host='pais.co.il', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2dd75b8490>, 'Connection to pais.co.il timed out. (connect timeout=2)'))","HTTPConnectionPool(host='pais.co.il', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2dd727b730>, 'Connection to pais.co.il timed out. (connect timeout=2)'))"
paknsaveonline.co.nz,"HTTPSConnectionPool(host='www.paknsaveonline.co.nz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.paknsaveonline.co.nz', port=443): Read timed out. (read timeout=2)"
pal-system.co.jp,"HTTPSConnectionPool(host='pal-system.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2dd73fdac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pal-system.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2dd750d460>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
palanga.lt,"HTTPSConnectionPool(host='palanga.lt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2dd72cf580>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='palanga.lt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2dd80df7f0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
palangostiltas.lt,"HTTPSConnectionPool(host='www.palangostiltas.lt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.palangostiltas.lt', port=443): Read timed out. (read timeout=2)"
palmers.co.nz,"HTTPSConnectionPool(host='www.palmers.co.nz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.palmers.co.nz', port=443): Read timed out. (read timeout=2)"
palmia.co.id,"HTTPSConnectionPool(host='palmia.co.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'palmia.co.id' doesn't match 'www.palmia.co.id'"")))","HTTPSConnectionPool(host='www.palmia.co.id', port=443): Read timed out. (read timeout=2)"
palmivillage.it,Exceeded 30 redirects.,Exceeded 30 redirects.
pami.org.ar,"HTTPSConnectionPool(host='pami.org.ar', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2dd7123b50>, 'Connection to pami.org.ar timed out. (connect timeout=2)'))","HTTPConnectionPool(host='www.pami.org.ar', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2dd7194340>, 'Connection to www.pami.org.ar timed out. (connect timeout=2)'))"
pamiatky.sk,"HTTPSConnectionPool(host='pamiatky.sk', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2dd57c2fa0>, 'Connection to pamiatky.sk timed out. (connect timeout=2)'))","HTTPConnectionPool(host='pamiatky.sk', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2dd70a1670>, 'Connection to pamiatky.sk timed out. (connect timeout=2)'))"
panspc.lt,"HTTPSConnectionPool(host='panspc.lt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2dd6d83dc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='panspc.lt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2dd38941c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
paolohospital.com,"HTTPSConnectionPool(host='paolohospital.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.paolohospital.com', port=443): Read timed out. (read timeout=2)"
parks.it,"HTTPSConnectionPool(host='parks.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2dd77ab1c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='parks.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2dd729ca90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
parlament.ch,Exceeded 30 redirects.,Exceeded 30 redirects.
parlament.gov.rs,"HTTPSConnectionPool(host='parlament.gov.rs', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2dd70397c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='parlament.gov.rs', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2dd76c0b80>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
parlamentnilisty.cz,"HTTPSConnectionPool(host='parlamentnilisty.cz', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2dd6e7af70>: Failed to establish a new connection: [Errno 113] No route to host'))","HTTPConnectionPool(host='parlamentnilisty.cz', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2dd5676df0>, 'Connection to parlamentnilisty.cz timed out. (connect timeout=2)'))"
parliament.go.th,"HTTPSConnectionPool(host='parliament.go.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2dd6e95910>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='parliament.go.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2dd71da640>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
parp.gov.pl,"HTTPSConnectionPool(host='parp.gov.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='parp.gov.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
partyalert.nl,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
pasgo.vn,"HTTPSConnectionPool(host='pasgo.vn', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='pasgo.vn', port=443): Read timed out. (read timeout=2)"
paslaugos24.lt,"HTTPSConnectionPool(host='paslaugos24.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.paslaugos24.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
