prakardproperty.com,"HTTPConnectionPool(host='www.prakardproperty.com', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.prakardproperty.com', port=80): Read timed out. (read timeout=2)"
praktis.bg,"HTTPSConnectionPool(host='praktis.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='praktis.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
precos.lv,"HTTPSConnectionPool(host='precos.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.precos.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
pref.aichi.jp,"HTTPSConnectionPool(host='pref.aichi.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89d540c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.aichi.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc89d540610>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.gunma.jp,"HTTPSConnectionPool(host='pref.gunma.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89d343610>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.gunma.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc89d36cdf0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.ibaraki.jp,"HTTPSConnectionPool(host='pref.ibaraki.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89d28c7f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.ibaraki.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc89d547850>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.kagoshima.jp,"HTTPSConnectionPool(host='pref.kagoshima.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89d362d00>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.kagoshima.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc89d3896d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.kanagawa.jp,"HTTPSConnectionPool(host='pref.kanagawa.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89d5407f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.kanagawa.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc89d3150d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.kyoto.jp,"HTTPSConnectionPool(host='pref.kyoto.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89d357d00>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.kyoto.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc89d31c8b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.miyagi.jp,"HTTPSConnectionPool(host='pref.miyagi.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89d28c430>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.miyagi.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc89d362e80>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.nara.jp,"HTTPSConnectionPool(host='pref.nara.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89d357f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.nara.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc89d2d6700>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.okayama.jp,"HTTPSConnectionPool(host='pref.okayama.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89d28c400>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.okayama.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc89d36cc70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.shizuoka.jp,"HTTPSConnectionPool(host='pref.shizuoka.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89d3393d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.shizuoka.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc89d28c370>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
prefeitura.sp.gov.br,"HTTPSConnectionPool(host='prefeitura.sp.gov.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc89d362070>, 'Connection to prefeitura.sp.gov.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='prefeitura.sp.gov.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc89d2f34c0>, 'Connection to prefeitura.sp.gov.br timed out. (connect timeout=2)'))"
prefettura.it,"HTTPSConnectionPool(host='prefettura.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'prefettura.it' doesn't match either of 'a248.e.akamai.net', '*.akamaized.net', '*.akamaihd-staging.net', '*.akamaihd.net', '*.akamaized-staging.net'"")))","HTTPConnectionPool(host='prefettura.it', port=80): Read timed out. (read timeout=2)"
preissuchmaschine.de,"HTTPSConnectionPool(host='preissuchmaschine.de', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='preissuchmaschine.de', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
presidencia.go.cr,"HTTPSConnectionPool(host='presidencia.go.cr', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='presidencia.go.cr', port=80): Read timed out. (read timeout=2)"
presidencia.gob.ec,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
pressbooks.pub,"HTTPSConnectionPool(host='pressbooks.pub', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='pressbooks.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
pressek.rs,"HTTPSConnectionPool(host='pressek.rs', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc89d1a6460>, 'Connection to pressek.rs timed out. (connect timeout=2)'))","HTTPConnectionPool(host='pressek.rs', port=80): Read timed out. (read timeout=2)"
priberam.org,"HTTPSConnectionPool(host='priberam.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89d1f8e80>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='priberam.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc89d3390d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pricee.vn,"HTTPSConnectionPool(host='pricee.vn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89d5618e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pricee.vn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc89d111df0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pricesworld.net,"HTTPSConnectionPool(host='www.pricesworld.net', port=443): Read timed out.","HTTPSConnectionPool(host='www.pricesworld.net', port=443): Read timed out."
prijs-trappen.be,"HTTPSConnectionPool(host='prijs-trappen.be', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89d36c400>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='prijs-trappen.be', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc89d12a490>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
prim.lt,"HTTPSConnectionPool(host='prim.lt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89d343430>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='www.prim.lt', port=80): Read timed out. (read timeout=2)"
printesaurbana.ro,"HTTPSConnectionPool(host='printesaurbana.ro', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89d1e4a00>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='printesaurbana.ro', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc89d111910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
prismamarket.ee,"HTTPSConnectionPool(host='prismamarket.ee', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='prismamarket.ee', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
priyo.com,"HTTPSConnectionPool(host='priyo.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='priyo.com', port=443): Read timed out. (read timeout=2)"
procuraduria.gov.co,"HTTPSConnectionPool(host='procuraduria.gov.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89d3399a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='procuraduria.gov.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc89d3150d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
prof.lv,"HTTPSConnectionPool(host='prof.lv', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='prof.lv', port=443): Read timed out. (read timeout=2)"
profesionalreview.com,"HTTPSConnectionPool(host='profesionalreview.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89d15f040>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPSConnectionPool(host='www.profesionalreview.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89d1c6160>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
promenad.hu,"HTTPSConnectionPool(host='www.promenad.hu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.promenad.hu', port=443): Read timed out. (read timeout=2)"
promenadanovisad.rs,"HTTPSConnectionPool(host='promenadanovisad.rs', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='promenadanovisad.rs', port=80): Read timed out. (read timeout=2)"
promerica.fi.cr,"HTTPSConnectionPool(host='promerica.fi.cr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89d1d8910>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='promerica.fi.cr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc89d2ca130>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
promodirecta.com.ar,"HTTPSConnectionPool(host='promodirecta.com.ar', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='promodirecta.com.ar', port=80): Read timed out. (read timeout=2)"
propertyshark.com,"HTTPSConnectionPool(host='www.propertyshark.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.propertyshark.com', port=443): Read timed out. (read timeout=2)"
propisi.com,"HTTPSConnectionPool(host='propisi.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPConnectionPool(host='propisi.com', port=80): Read timed out. (read timeout=2)"
proptiger.com,"HTTPSConnectionPool(host='www.proptiger.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.proptiger.com', port=443): Read timed out. (read timeout=2)"
proshareng.com,"HTTPSConnectionPool(host='www.proshareng.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.proshareng.com', port=443): Read timed out. (read timeout=2)"
protexin.hu,Exceeded 30 redirects.,Exceeded 30 redirects.
protis.hr,"HTTPSConnectionPool(host='www.protis.hr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.protis.hr', port=443): Read timed out. (read timeout=2)"
protoporia.gr,"HTTPSConnectionPool(host='protoporia.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'protoporia.gr' doesn't match 'www.protoporia.gr'"")))",Exceeded 30 redirects.
protothema.gr,"HTTPSConnectionPool(host='protothema.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.protothema.gr', port=443): Read timed out. (read timeout=2)"
provincia.tn.it,"HTTPSConnectionPool(host='provincia.tn.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89ccf3dc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='provincia.tn.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc89d561c70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
psd.gov.jo,"HTTPSConnectionPool(host='psd.gov.jo', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='psd.gov.jo', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
psiquiatria.com,"HTTPSConnectionPool(host='psiquiatria.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='psiquiatria.com', port=443): Read timed out. (read timeout=2)"
pta.gov.pk,"HTTPSConnectionPool(host='pta.gov.pk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='pta.gov.pk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
pub.ro,"HTTPSConnectionPool(host='pub.ro', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89d362df0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pub.ro', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc89db3ff40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
publishing.service.gov.uk,"HTTPSConnectionPool(host='publishing.service.gov.uk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89b2715e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='publishing.service.gov.uk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc89d02ee20>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
puc-rio.br,"HTTPSConnectionPool(host='puc-rio.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89d1a6fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='puc-rio.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc89db24310>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
puce.edu.ec,"HTTPSConnectionPool(host='puce.edu.ec', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89c125ca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='puce.edu.ec', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc89c0d0e20>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pucgoias.edu.br,"HTTPSConnectionPool(host='pucgoias.edu.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc89d205bb0>, 'Connection to pucgoias.edu.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='pucgoias.edu.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc89c139be0>, 'Connection to pucgoias.edu.br timed out. (connect timeout=2)'))"
punjab.gov.pk,"HTTPSConnectionPool(host='punjab.gov.pk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89cf4a7f0>: Failed to establish a new connection: [Errno 113] No route to host'))","HTTPConnectionPool(host='punjab.gov.pk', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc89db24a90>, 'Connection to punjab.gov.pk timed out. (connect timeout=2)'))"
pupulandia.fi,"HTTPSConnectionPool(host='pupulandia.fi', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='pupulandia.fi', port=443): Read timed out. (read timeout=2)"
pycca.com,"HTTPSConnectionPool(host='pycca.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89b27c1c0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='pycca.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc89cf0c910>: Failed to establish a new connection: [Errno 111] Connection refused'))"
pylimas.lt,"HTTPSConnectionPool(host='pylimas.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='pylimas.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
qatips.net,"HTTPSConnectionPool(host='qatips.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='qatips.net', port=443): Read timed out. (read timeout=2)"
qroo.gob.mx,"HTTPSConnectionPool(host='qroo.gob.mx', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='qroo.gob.mx', port=443): Read timed out. (read timeout=2)"
quangbinh.gov.vn,"HTTPSConnectionPool(host='quangbinh.gov.vn', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.quangbinh.gov.vn', port=443): Read timed out. (read timeout=2)"
quedigital.com.ar,"HTTPSConnectionPool(host='quedigital.com.ar', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='quedigital.com.ar', port=443): Read timed out. (read timeout=2)"
quito.gob.ec,"HTTPSConnectionPool(host='quito.gob.ec', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='quito.gob.ec', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc89ccf8a60>, 'Connection to quito.gob.ec timed out. (connect timeout=2)'))"
raa.se,"HTTPSConnectionPool(host='raa.se', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='raa.se', port=443): Read timed out. (read timeout=2)"
radenfatah.ac.id,"HTTPSConnectionPool(host='radenfatah.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='radenfatah.ac.id', port=443): Read timed out. (read timeout=2)"
radiocampanario.com,"HTTPSConnectionPool(host='radiocampanario.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.radiocampanario.com', port=443): Read timed out. (read timeout=2)"
radiokim.net,"HTTPSConnectionPool(host='www.radiokim.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.radiokim.net', port=443): Read timed out. (read timeout=2)"
radiomundial.com.ve,"HTTPSConnectionPool(host='radiomundial.com.ve', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc89cf3df70>, 'Connection to radiomundial.com.ve timed out. (connect timeout=2)'))","HTTPConnectionPool(host='radiomundial.com.ve', port=80): Read timed out. (read timeout=2)"
radiopopular.pt,"HTTPSConnectionPool(host='radiopopular.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'radiopopular.pt' doesn't match '*.radiopopular.pt'"")))","HTTPSConnectionPool(host='radiopopular.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'radiopopular.pt' doesn't match '*.radiopopular.pt'"")))"
radioromaniacultural.ro,"HTTPSConnectionPool(host='www.radioromaniacultural.ro', port=443): Read timed out.","HTTPSConnectionPool(host='www.radioromaniacultural.ro', port=443): Read timed out."
radiosantafe.com,"HTTPSConnectionPool(host='radiosantafe.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'radiosantafe.com' doesn't match 'www.radiosantafe.com'"")))","HTTPConnectionPool(host='radiosantafe.com', port=80): Read timed out. (read timeout=2)"
raiceshandcrafts.com,"HTTPSConnectionPool(host='raiceshandcrafts.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89b271040>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='raiceshandcrafts.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc89cc5a070>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
raiffeisen.ro,"('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: invalid code lengths set'))","('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: invalid code lengths set'))"
rakuten.co.jp,"HTTPSConnectionPool(host='www.rakuten.co.jp', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.rakuten.co.jp', port=443): Read timed out. (read timeout=2)"
rakuten.com.tw,"HTTPSConnectionPool(host='www.rakuten.com.tw', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.rakuten.com.tw', port=443): Read timed out. (read timeout=2)"
rakuten.ne.jp,"HTTPSConnectionPool(host='rakuten.ne.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89b34fd30>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='rakuten.ne.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc89cc4d850>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ralphs.com,"HTTPSConnectionPool(host='ralphs.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc89cc7bca0>, 'Connection to ralphs.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='www.ralphs.com', port=80): Read timed out. (read timeout=2)"
ramajudicial.gov.co,"HTTPSConnectionPool(host='ramajudicial.gov.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc89cc915b0>, 'Connection to ramajudicial.gov.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ramajudicial.gov.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc89cef77c0>, 'Connection to ramajudicial.gov.co timed out. (connect timeout=2)'))"
rchsd.org,"HTTPSConnectionPool(host='rchsd.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc89cec1190>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='rchsd.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc89b289130>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
rdpad.lv,"HTTPSConnectionPool(host='rdpad.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='rdpad.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
rdvmedicaux.com,"HTTPSConnectionPool(host='rdvmedicaux.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'rdvmedicaux.com' doesn't match '*.rdvmedicaux.ccs.cegedim.cloud'"")))","HTTPSConnectionPool(host='rdvmedicaux.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'rdvmedicaux.com' doesn't match '*.rdvmedicaux.ccs.cegedim.cloud'"")))"
