prakardproperty.com,"HTTPConnectionPool(host='www.prakardproperty.com', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.prakardproperty.com', port=80): Read timed out. (read timeout=2)"
praktis.bg,"HTTPSConnectionPool(host='praktis.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='praktis.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
pralanna.com,"HTTPSConnectionPool(host='pralanna.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)')))","HTTPConnectionPool(host='pralanna.com', port=80): Read timed out. (read timeout=2)"
prathaprachan-mag.com,"HTTPSConnectionPool(host='prathaprachan-mag.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='prathaprachan-mag.com', port=443): Read timed out. (read timeout=2)"
pravatami.bg,"HTTPSConnectionPool(host='pravatami.bg', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='pravatami.bg', port=80): Read timed out. (read timeout=2)"
precos.lv,"HTTPSConnectionPool(host='precos.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.precos.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
pref.aichi.jp,"HTTPSConnectionPool(host='pref.aichi.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2aab7eee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.aichi.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2ac04bc10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.gunma.jp,"HTTPSConnectionPool(host='pref.gunma.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2ad54dc10>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.gunma.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2ac99ca90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.ibaraki.jp,"HTTPSConnectionPool(host='pref.ibaraki.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2aaa83e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.ibaraki.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2abe6b6a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.kagoshima.jp,"HTTPSConnectionPool(host='pref.kagoshima.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2acadd880>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.kagoshima.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2aba6d4c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.kanagawa.jp,"HTTPSConnectionPool(host='pref.kanagawa.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2ac937460>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.kanagawa.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2ab9d47f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.kyoto.jp,"HTTPSConnectionPool(host='pref.kyoto.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2aae16130>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.kyoto.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2ab757a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.miyagi.jp,"HTTPSConnectionPool(host='pref.miyagi.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2aa88dc10>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.miyagi.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2ab5520d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.nara.jp,"HTTPSConnectionPool(host='pref.nara.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2aa99cdf0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.nara.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2aae79a00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.okayama.jp,"HTTPSConnectionPool(host='pref.okayama.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2ad479a60>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.okayama.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2aac58dc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pref.shizuoka.jp,"HTTPSConnectionPool(host='pref.shizuoka.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2ac99cbe0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pref.shizuoka.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2aa8822e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
preissuchmaschine.de,"HTTPSConnectionPool(host='preissuchmaschine.de', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='preissuchmaschine.de', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
prensalibre.com,"HTTPSConnectionPool(host='www.prensalibre.com', port=443): Read timed out.","HTTPSConnectionPool(host='www.prensalibre.com', port=443): Read timed out."
presidencia.go.cr,"HTTPSConnectionPool(host='presidencia.go.cr', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='presidencia.go.cr', port=80): Read timed out. (read timeout=2)"
presidencia.gob.ec,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
pressbooks.pub,"HTTPSConnectionPool(host='pressbooks.pub', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='pressbooks.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
priberam.org,"HTTPSConnectionPool(host='priberam.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'priberam.org' doesn't match either of 'www.priberam.pt', 'priberam.pt', 'www.legix.pt', 'dicionario.priberam.org', 'store.priberam.pt', '2016.legix.pt', 'www.flip.pt', 'oanoempalavras.pt', 'app.legix.pt', '*.priberam.com', 'monitio-project.eu', 'plain-x.com', 'app.plain-x.com', 'www.monitio-project.eu', 'staging.plain-x.com'"")))","HTTPSConnectionPool(host='priberam.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'priberam.org' doesn't match either of 'www.priberam.pt', 'priberam.pt', 'www.legix.pt', 'dicionario.priberam.org', 'store.priberam.pt', '2016.legix.pt', 'www.flip.pt', 'oanoempalavras.pt', 'app.legix.pt', '*.priberam.com', 'monitio-project.eu', 'plain-x.com', 'app.plain-x.com', 'www.monitio-project.eu', 'staging.plain-x.com'"")))"
price.tn,"HTTPSConnectionPool(host='www.price.tn', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.price.tn', port=443): Read timed out. (read timeout=2)"
pricee.vn,"HTTPSConnectionPool(host='pricee.vn', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='pricee.vn', port=443): Read timed out. (read timeout=2)"
pricesworld.net,"HTTPSConnectionPool(host='www.pricesworld.net', port=443): Read timed out.","HTTPSConnectionPool(host='www.pricesworld.net', port=443): Read timed out."
prijs-trappen.be,"HTTPSConnectionPool(host='prijs-trappen.be', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2a9189cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='prijs-trappen.be', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2a9ab45e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
prim.lt,"HTTPSConnectionPool(host='prim.lt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2ab5b76a0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='www.prim.lt', port=80): Read timed out. (read timeout=2)"
prmtns.co,"HTTPSConnectionPool(host='prmtns.co', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='prmtns.co', port=80): Read timed out. (read timeout=2)"
procuraduria.gov.co,"HTTPSConnectionPool(host='procuraduria.gov.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2ab02e160>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='procuraduria.gov.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2ad1a40a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
prof.lv,"HTTPSConnectionPool(host='prof.lv', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='prof.lv', port=443): Read timed out. (read timeout=2)"
profiremont.sk,"HTTPSConnectionPool(host='profiremont.sk', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='profiremont.sk', port=80): Read timed out. (read timeout=2)"
prokosmeetika.ee,"HTTPSConnectionPool(host='prokosmeetika.ee', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='prokosmeetika.ee', port=443): Read timed out. (read timeout=2)"
promenad.hu,"HTTPSConnectionPool(host='www.promenad.hu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.promenad.hu', port=443): Read timed out. (read timeout=2)"
promenadanovisad.rs,"HTTPSConnectionPool(host='promenadanovisad.rs', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='promenadanovisad.rs', port=80): Read timed out. (read timeout=2)"
promerica.fi.cr,"HTTPSConnectionPool(host='promerica.fi.cr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2ad0d7400>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='promerica.fi.cr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2a5232610>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
promodirecta.com.ar,"HTTPSConnectionPool(host='promodirecta.com.ar', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1124)')))","HTTPConnectionPool(host='www.promodirecta.com.ar', port=80): Read timed out. (read timeout=2)"
property.com.au,"HTTPSConnectionPool(host='www.property.com.au', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.property.com.au', port=443): Read timed out. (read timeout=2)"
propisi.com,"HTTPSConnectionPool(host='propisi.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPConnectionPool(host='propisi.com', port=80): Read timed out. (read timeout=2)"
proshareng.com,"HTTPSConnectionPool(host='www.proshareng.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.proshareng.com', port=443): Read timed out. (read timeout=2)"
protexin.hu,Exceeded 30 redirects.,Exceeded 30 redirects.
protis.hr,"HTTPSConnectionPool(host='www.protis.hr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.protis.hr', port=443): Read timed out. (read timeout=2)"
protoporia.gr,"HTTPSConnectionPool(host='protoporia.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'protoporia.gr' doesn't match 'www.protoporia.gr'"")))",Exceeded 30 redirects.
provincia.tn.it,"HTTPSConnectionPool(host='provincia.tn.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2aab74250>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='provincia.tn.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2a4914340>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
provisible.nl,"HTTPSConnectionPool(host='provisible.nl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2a46616a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='provisible.nl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2a243d280>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
psd.gov.jo,"HTTPSConnectionPool(host='psd.gov.jo', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='psd.gov.jo', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
psiquiatria.com,"HTTPSConnectionPool(host='psiquiatria.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='psiquiatria.com', port=443): Read timed out. (read timeout=2)"
pta.gov.pk,"HTTPSConnectionPool(host='pta.gov.pk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='pta.gov.pk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
ptt.gov.tr,"HTTPSConnectionPool(host='ptt.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb2ac7f68e0>, 'Connection to ptt.gov.tr timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ptt.gov.tr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb2a53c4670>, 'Connection to ptt.gov.tr timed out. (connect timeout=2)'))"
pub.ro,"HTTPSConnectionPool(host='pub.ro', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2a65c4220>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pub.ro', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2a3fe0460>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
public-welfare.com,"HTTPSConnectionPool(host='public-welfare.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='public-welfare.com', port=443): Read timed out. (read timeout=2)"
publishing.service.gov.uk,"HTTPSConnectionPool(host='publishing.service.gov.uk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2ab4afe20>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='publishing.service.gov.uk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2a549f0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
puc-rio.br,"HTTPSConnectionPool(host='puc-rio.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2ac120a00>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='puc-rio.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2a8aefd60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
puce.edu.ec,"HTTPSConnectionPool(host='puce.edu.ec', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2a5822dc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='puce.edu.ec', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2a7d20d60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pucgoias.edu.br,"HTTPSConnectionPool(host='pucgoias.edu.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb2a6ab74f0>, 'Connection to pucgoias.edu.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='pucgoias.edu.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb2a3316a90>, 'Connection to pucgoias.edu.br timed out. (connect timeout=2)'))"
punjab.gov.pk,"HTTPSConnectionPool(host='punjab.gov.pk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2a6e2e4f0>: Failed to establish a new connection: [Errno 113] No route to host'))","HTTPConnectionPool(host='punjab.gov.pk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2a566dd00>: Failed to establish a new connection: [Errno 113] No route to host'))"
pupulandia.fi,"HTTPSConnectionPool(host='pupulandia.fi', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='pupulandia.fi', port=443): Read timed out. (read timeout=2)"
pycca.com,"HTTPSConnectionPool(host='pycca.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2ad0467c0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='pycca.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2ab138f40>: Failed to establish a new connection: [Errno 111] Connection refused'))"
pylimas.lt,"HTTPSConnectionPool(host='pylimas.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='pylimas.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
qatips.net,"HTTPSConnectionPool(host='qatips.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='qatips.net', port=443): Read timed out. (read timeout=2)"
quangninh.gov.vn,"HTTPSConnectionPool(host='quangninh.gov.vn', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='quangninh.gov.vn', port=443): Read timed out. (read timeout=2)"
quedigital.com.ar,"HTTPSConnectionPool(host='quedigital.com.ar', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='quedigital.com.ar', port=443): Read timed out. (read timeout=2)"
quito.gob.ec,"HTTPSConnectionPool(host='quito.gob.ec', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='quito.gob.ec', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb2acab75e0>, 'Connection to quito.gob.ec timed out. (connect timeout=2)'))"
quochoi.vn,"HTTPSConnectionPool(host='quochoi.vn', port=443): Read timed out. (read timeout=2)","('Connection aborted.', UnknownProtocol('HTTP/'))"
quus.net,"HTTPSConnectionPool(host='quus.net', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='quus.net', port=80): Read timed out. (read timeout=2)"
raanana.muni.il,"HTTPSConnectionPool(host='raanana.muni.il', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb2a9df25b0>, 'Connection to raanana.muni.il timed out. (connect timeout=2)'))","HTTPConnectionPool(host='raanana.muni.il', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb2ab3ebb20>, 'Connection to raanana.muni.il timed out. (connect timeout=2)'))"
rabim.info,"HTTPSConnectionPool(host='rabim.info', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb2ab6a2f40>, 'Connection to rabim.info timed out. (connect timeout=2)'))","HTTPConnectionPool(host='www.rabim.info', port=80): Read timed out. (read timeout=2)"
radioformula.com.mx,"HTTPSConnectionPool(host='radioformula.com.mx', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.radioformula.com.mx', port=443): Read timed out. (read timeout=2)"
radiomundial.com.ve,"HTTPSConnectionPool(host='radiomundial.com.ve', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb2ab4560d0>, 'Connection to radiomundial.com.ve timed out. (connect timeout=2)'))","HTTPConnectionPool(host='radiomundial.com.ve', port=80): Read timed out. (read timeout=2)"
radiopopular.pt,"HTTPSConnectionPool(host='radiopopular.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'radiopopular.pt' doesn't match '*.radiopopular.pt'"")))","HTTPSConnectionPool(host='radiopopular.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'radiopopular.pt' doesn't match '*.radiopopular.pt'"")))"
radioromaniacultural.ro,"HTTPSConnectionPool(host='www.radioromaniacultural.ro', port=443): Read timed out.","HTTPSConnectionPool(host='www.radioromaniacultural.ro', port=443): Read timed out."
radiosago.cl,"HTTPSConnectionPool(host='radiosago.cl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='radiosago.cl', port=443): Read timed out. (read timeout=2)"
radiosantafe.com,"HTTPSConnectionPool(host='radiosantafe.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'radiosantafe.com' doesn't match 'www.radiosantafe.com'"")))","HTTPConnectionPool(host='radiosantafe.com', port=80): Read timed out. (read timeout=2)"
raiffeisen.ro,"('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: invalid code lengths set'))","('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: invalid code lengths set'))"
rakuten.co.jp,"HTTPSConnectionPool(host='www.rakuten.co.jp', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.rakuten.co.jp', port=443): Read timed out. (read timeout=2)"
rakuten.com.tw,"HTTPSConnectionPool(host='www.rakuten.com.tw', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.rakuten.com.tw', port=443): Read timed out. (read timeout=2)"
rakuten.ne.jp,"HTTPSConnectionPool(host='rakuten.ne.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2ad75d880>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='rakuten.ne.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2ac14a310>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ralphs.com,"HTTPSConnectionPool(host='ralphs.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb2abe29c40>, 'Connection to ralphs.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='www.ralphs.com', port=80): Read timed out. (read timeout=2)"
ramajudicial.gov.co,"HTTPSConnectionPool(host='ramajudicial.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPConnectionPool(host='ramajudicial.gov.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb2ad6733a0>, 'Connection to ramajudicial.gov.co timed out. (connect timeout=2)'))"
rchsd.org,"HTTPSConnectionPool(host='rchsd.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2ad6d29d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='rchsd.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2ac6fadc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
rdpad.lv,"HTTPSConnectionPool(host='rdpad.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='rdpad.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
rdvmedicaux.com,"HTTPSConnectionPool(host='rdvmedicaux.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'rdvmedicaux.com' doesn't match '*.rdvmedicaux.ccs.cegedim.cloud'"")))","HTTPSConnectionPool(host='rdvmedicaux.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'rdvmedicaux.com' doesn't match '*.rdvmedicaux.ccs.cegedim.cloud'"")))"
