recepti.pl,"HTTPSConnectionPool(host='recepti.pl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.recepti.pl', port=443): Read timed out. (read timeout=2)"
receptizasvakog.com,"HTTPSConnectionPool(host='receptizasvakog.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='receptizasvakog.com', port=443): Read timed out. (read timeout=2)"
receptkollekcio.com,"HTTPSConnectionPool(host='receptkollekcio.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f87931df0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='receptkollekcio.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f86e0c5b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
recipe-blog.jp,"HTTPSConnectionPool(host='www.recipe-blog.jp', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.recipe-blog.jp', port=443): Read timed out. (read timeout=2)"
recruit.se,"HTTPSConnectionPool(host='recruit.se', port=443): Read timed out.","HTTPConnectionPool(host='recruit.se', port=80): Read timed out."
redcross.or.th,"HTTPSConnectionPool(host='redcross.or.th', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1124)')))","HTTPSConnectionPool(host='redcross.or.th', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1124)')))"
reddit.com,"HTTPSConnectionPool(host='www.reddit.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.reddit.com', port=443): Read timed out. (read timeout=2)"
referat.ro,"HTTPSConnectionPool(host='referat.ro', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.referat.ro', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
refertimacuan.com,"HTTPSConnectionPool(host='refertimacuan.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='refertimacuan.com', port=443): Read timed out. (read timeout=2)"
regionalobala.si,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
regione.fvg.it,"HTTPSConnectionPool(host='regione.fvg.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f87697370>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='regione.fvg.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f85083070>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
regione.piemonte.it,"HTTPSConnectionPool(host='regione.piemonte.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f854ff8b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='regione.piemonte.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f8503c0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
registraduria.gov.co,"HTTPSConnectionPool(host='registraduria.gov.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6f89ba62b0>, 'Connection to registraduria.gov.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='registraduria.gov.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6f858ab760>, 'Connection to registraduria.gov.co timed out. (connect timeout=2)'))"
registrocivil.gob.ec,"HTTPSConnectionPool(host='registrocivil.gob.ec', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.registrocivil.gob.ec', port=443): Read timed out. (read timeout=2)"
repairpal.com,"HTTPSConnectionPool(host='repairpal.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f828d1df0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='repairpal.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f8a20f880>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
repositorioinstitucional.mx,"HTTPSConnectionPool(host='repositorioinstitucional.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f89574f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='repositorioinstitucional.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f841fa340>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
republica.com.uy,"HTTPSConnectionPool(host='republica.com.uy', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f89733550>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='republica.com.uy', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f82aed310>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
resepmasakanku.net,"HTTPSConnectionPool(host='resepmasakanku.net', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='resepmasakanku.net', port=80): Read timed out. (read timeout=2)"
residences.in.th,"HTTPSConnectionPool(host='www.residences.in.th', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.residences.in.th', port=443): Read timed out. (read timeout=2)"
rest.co.il,"HTTPSConnectionPool(host='rest.co.il', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPConnectionPool(host='rest.co.il', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6f8290daf0>, 'Connection to rest.co.il timed out. (connect timeout=2)'))"
revistaei.cl,"HTTPSConnectionPool(host='revistaei.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f8a1b1e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='revistaei.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f8936e2b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
revistasbolivianas.org.bo,"HTTPSConnectionPool(host='revistasbolivianas.org.bo', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f82aed9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='revistasbolivianas.org.bo', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6f89398580>, 'Connection to revistasbolivianas.org.bo timed out. (connect timeout=2)'))"
rgboutique.it,"HTTPSConnectionPool(host='rgboutique.it', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='rgboutique.it', port=80): Read timed out. (read timeout=2)"
ribeiro.com.ar,"HTTPSConnectionPool(host='ribeiro.com.ar', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'ribeiro.com.ar' doesn't match '*.ribeiro.com.ar'"")))","HTTPSConnectionPool(host='ribeiro.com.ar', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'ribeiro.com.ar' doesn't match '*.ribeiro.com.ar'"")))"
ric.si,"HTTPSConnectionPool(host='ric.si', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f887e80a0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='ric.si', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f86faa340>: Failed to establish a new connection: [Errno 111] Connection refused'))"
richmondfuture.org,"HTTPSConnectionPool(host='richmondfuture.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f8961d9d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='richmondfuture.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f886f1eb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
rickid.nl,"HTTPSConnectionPool(host='rickid.nl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f85887040>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='rickid.nl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f88087700>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
rid.go.th,"HTTPSConnectionPool(host='rid.go.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f88827d60>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='rid.go.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f82aedfd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
ridebuster.com,"HTTPSConnectionPool(host='ridebuster.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='ridebuster.com', port=80): Read timed out. (read timeout=2)"
rikunabi.com,"HTTPSConnectionPool(host='rikunabi.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f898477c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='rikunabi.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f89597bb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
rington.io,"HTTPSConnectionPool(host='rington.io', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPConnectionPool(host='rington.io', port=80): Read timed out. (read timeout=2)"
rionegro.com.ar,"HTTPSConnectionPool(host='www.rionegro.com.ar', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.rionegro.com.ar', port=443): Read timed out. (read timeout=2)"
rishonlezion.muni.il,"HTTPSConnectionPool(host='rishonlezion.muni.il', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6f81550af0>, 'Connection to rishonlezion.muni.il timed out. (connect timeout=2)'))","HTTPConnectionPool(host='rishonlezion.muni.il', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6f88790e80>, 'Connection to rishonlezion.muni.il timed out. (connect timeout=2)'))"
ristekdikti.go.id,"HTTPSConnectionPool(host='ristekdikti.go.id', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6f892217c0>, 'Connection to ristekdikti.go.id timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ristekdikti.go.id', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6f88f45c70>, 'Connection to ristekdikti.go.id timed out. (connect timeout=2)'))"
ritsumei.ac.jp,"HTTPSConnectionPool(host='ritsumei.ac.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f88fa2220>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ritsumei.ac.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f829199d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
rivera.gub.uy,"HTTPSConnectionPool(host='rivera.gub.uy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='rivera.gub.uy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
rmu.ac.th,"HTTPSConnectionPool(host='rmu.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f828bad60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='rmu.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f89ae18e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
rmutr.ac.th,"HTTPSConnectionPool(host='rmutr.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f86f8c310>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='rmutr.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f88ccd5e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
robinson.co.th,"HTTPSConnectionPool(host='robinson.co.th', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.robinson.co.th', port=443): Read timed out. (read timeout=2)"
romania-actualitati.ro,"HTTPSConnectionPool(host='romania-actualitati.ro', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f874161f0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='www.romania-actualitati.ro', port=80): Read timed out. (read timeout=2)"
rotise.gr,"HTTPSConnectionPool(host='rotise.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1124)')))",Exceeded 30 redirects.
rqiim.com,"HTTPSConnectionPool(host='www.rqiim.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.rqiim.com', port=443): Read timed out. (read timeout=2)"
rri.ro,"HTTPSConnectionPool(host='rri.ro', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'rri.ro' doesn't match 'www.rri.ro'"")))","HTTPSConnectionPool(host='www.rri.ro', port=443): Read timed out. (read timeout=2)"
rs-online.com,"HTTPSConnectionPool(host='rs-online.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f815387c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='rs-online.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f882bfa60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
rs.ba,"HTTPSConnectionPool(host='rs.ba', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f85cfb0a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='rs.ba', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f829191f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
rtk.rs,"HTTPSConnectionPool(host='www.rtk.rs', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.rtk.rs', port=443): Read timed out. (read timeout=2)"
rtm.gov.my,"HTTPSConnectionPool(host='rtm.gov.my', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f80936fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='rtm.gov.my', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f8678b1c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
rttuotetieto.fi,"HTTPSConnectionPool(host='rttuotetieto.fi', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'rttuotetieto.fi' doesn't match either of 'www.rttuotetieto.fi', 'urakoitsija.rttuotetieto.fi'"")))","HTTPSConnectionPool(host='www.rttuotetieto.fi', port=443): Read timed out. (read timeout=2)"
rtvmag.co.rs,"HTTPSConnectionPool(host='rtvmag.co.rs', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f8777d0a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='rtvmag.co.rs', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f88ec28b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ru.ac.th,"HTTPSConnectionPool(host='ru.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f88db7dc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ru.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f887e8880>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
rumahbelajar.id,"HTTPSConnectionPool(host='rumahbelajar.id', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f8884a2e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='rumahbelajar.id', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f81cc9df0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ruten.com.tw,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
rvb.lt,"HTTPSConnectionPool(host='rvb.lt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f85887d00>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='rvb.lt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f89810640>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
rvvg.lv,"HTTPSConnectionPool(host='rvvg.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.rvvg.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
rzp.cz,"HTTPSConnectionPool(host='rzp.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1124)')))","HTTPConnectionPool(host='rzp.cz', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6f87767730>, 'Connection to rzp.cz timed out. (connect timeout=2)'))"
saabturboclub.com,"HTTPSConnectionPool(host='saabturboclub.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f854ab2e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='saabturboclub.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f880e4eb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sabcnews.com,"HTTPSConnectionPool(host='www.sabcnews.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sabcnews.com', port=443): Read timed out. (read timeout=2)"
saberingles.com.ar,"HTTPSConnectionPool(host='saberingles.com.ar', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6f85d4f760>, 'Connection to saberingles.com.ar timed out. (connect timeout=2)'))","HTTPConnectionPool(host='saberingles.com.ar', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6f89398ca0>, 'Connection to saberingles.com.ar timed out. (connect timeout=2)'))"
sachvui.com,"HTTPSConnectionPool(host='sachvui.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='sachvui.com', port=443): Read timed out. (read timeout=2)"
sacombank.com.vn,"HTTPSConnectionPool(host='www.sacombank.com.vn', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sacombank.com.vn', port=443): Read timed out. (read timeout=2)"
saflii.org,"HTTPSConnectionPool(host='saflii.org', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='saflii.org', port=80): Read timed out. (read timeout=2)"
sageyogact.com,"HTTPConnectionPool(host='www.sageyogact.com', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='sageyogact.com', port=80): Read timed out. (read timeout=2)"
sahibinden.com,"HTTPSConnectionPool(host='sahibinden.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='sahibinden.com', port=80): Read timed out. (read timeout=2)"
sahibinden.com.tr,"HTTPSConnectionPool(host='sahibinden.com.tr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: TLSV1_UNRECOGNIZED_NAME] tlsv1 unrecognized name (_ssl.c:1124)')))","HTTPConnectionPool(host='sahibinden.com.tr', port=80): Read timed out. (read timeout=2)"
sahistory.org.za,"HTTPSConnectionPool(host='sahistory.org.za', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='sahistory.org.za', port=443): Read timed out. (read timeout=2)"
sahra.org.za,"HTTPSConnectionPool(host='sahra.org.za', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='sahra.org.za', port=80): Read timed out. (read timeout=2)"
saitama.lg.jp,"HTTPSConnectionPool(host='saitama.lg.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f8a57eee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='saitama.lg.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f87015700>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
saldus.lv,"HTTPSConnectionPool(host='saldus.lv', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6f8837da60>, 'Connection to saldus.lv timed out. (connect timeout=2)'))","HTTPConnectionPool(host='saldus.lv', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6f887e8c40>, 'Connection to saldus.lv timed out. (connect timeout=2)'))"
salika.co,"HTTPSConnectionPool(host='salika.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'salika.co' doesn't match 'www.salika.co'"")))","HTTPSConnectionPool(host='salika.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'salika.co' doesn't match 'www.salika.co'"")))"
