realo.be,"HTTPSConnectionPool(host='www.realo.be', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.realo.be', port=443): Read timed out. (read timeout=2)"
receptizasvakog.com,"HTTPSConnectionPool(host='receptizasvakog.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='receptizasvakog.com', port=443): Read timed out. (read timeout=2)"
receptkollekcio.com,"HTTPSConnectionPool(host='receptkollekcio.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f12fce7af70>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='receptkollekcio.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12fcf0bf10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
recruit.se,"HTTPSConnectionPool(host='recruit.se', port=443): Read timed out.","HTTPConnectionPool(host='recruit.se', port=80): Read timed out."
redcross.or.th,"HTTPSConnectionPool(host='redcross.or.th', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1124)')))","HTTPSConnectionPool(host='redcross.or.th', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1124)')))"
referat.ro,"HTTPSConnectionPool(host='referat.ro', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.referat.ro', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
refertimacuan.com,"HTTPSConnectionPool(host='refertimacuan.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='refertimacuan.com', port=443): Read timed out. (read timeout=2)"
regionalobala.si,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
regione.fvg.it,"HTTPSConnectionPool(host='regione.fvg.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f12fcbd3b20>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='regione.fvg.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12fce7ae80>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
regione.piemonte.it,"HTTPSConnectionPool(host='regione.piemonte.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f12fcb754c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='regione.piemonte.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12fcb8e2e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
registraduria.gov.co,"HTTPSConnectionPool(host='registraduria.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'registraduria.gov.co' doesn't match '*.registraduria.gov.co'"")))","HTTPSConnectionPool(host='registraduria.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'registraduria.gov.co' doesn't match '*.registraduria.gov.co'"")))"
registrocivil.gob.ec,"HTTPSConnectionPool(host='registrocivil.gob.ec', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.registrocivil.gob.ec', port=443): Read timed out. (read timeout=2)"
relaxtrip2018.com,"HTTPSConnectionPool(host='www.relaxtrip2018.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.relaxtrip2018.com', port=443): Read timed out. (read timeout=2)"
remax.com.tr,"HTTPSConnectionPool(host='remax.com.tr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.remax.com.tr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
remax.ro,"HTTPSConnectionPool(host='www.remax.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.remax.ro', port=443): Read timed out. (read timeout=2)"
repairpal.com,"HTTPSConnectionPool(host='repairpal.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f12fcafd370>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='repairpal.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12fca45ee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
repositorioinstitucional.mx,"HTTPSConnectionPool(host='repositorioinstitucional.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f12fc8b8d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='repositorioinstitucional.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12fc8c4550>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
republica.com.uy,"HTTPSConnectionPool(host='republica.com.uy', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f12fc843ac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='republica.com.uy', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12fc7aefd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
resepmasakanku.net,"HTTPSConnectionPool(host='resepmasakanku.net', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='resepmasakanku.net', port=80): Read timed out. (read timeout=2)"
resett.no,"HTTPSConnectionPool(host='resett.no', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='resett.no', port=443): Read timed out. (read timeout=2)"
residenzak1.it,Exceeded 30 redirects.,Exceeded 30 redirects.
ressourcen.dk,"HTTPSConnectionPool(host='ressourcen.dk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f12fca8eaf0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ressourcen.dk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12fc8b8520>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
restaurantbuffalo.dk,"HTTPSConnectionPool(host='restaurantbuffalo.dk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f12fcae8640>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='restaurantbuffalo.dk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12fcc3b970>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
revistaei.cl,"HTTPSConnectionPool(host='revistaei.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f12fb188e80>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='revistaei.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12fbdcc580>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ribeiro.com.ar,"HTTPSConnectionPool(host='ribeiro.com.ar', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f12fb1af220>, 'Connection to ribeiro.com.ar timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ribeiro.com.ar', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f12fb2b5580>, 'Connection to ribeiro.com.ar timed out. (connect timeout=2)'))"
ric.si,"HTTPSConnectionPool(host='ric.si', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f12fb24deb0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='ric.si', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12fb16e310>: Failed to establish a new connection: [Errno 111] Connection refused'))"
ricardoeletro.com.br,"HTTPSConnectionPool(host='ricardoeletro.com.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f12fb1a1ee0>, 'Connection to ricardoeletro.com.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ricardoeletro.com.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f12fb33d4f0>, 'Connection to ricardoeletro.com.br timed out. (connect timeout=2)'))"
rid.go.th,"HTTPSConnectionPool(host='rid.go.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f12fb37d880>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
ridebuster.com,"HTTPSConnectionPool(host='ridebuster.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='ridebuster.com', port=80): Read timed out. (read timeout=2)"
rikunabi.com,"HTTPSConnectionPool(host='rikunabi.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f12fb37abe0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='rikunabi.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12fbe2a910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
rington.io,"HTTPSConnectionPool(host='rington.io', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='rington.io', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
ristekdikti.go.id,"HTTPSConnectionPool(host='ristekdikti.go.id', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f12fc969370>, 'Connection to ristekdikti.go.id timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ristekdikti.go.id', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12fb3c36d0>: Failed to establish a new connection: [Errno 113] No route to host'))"
ritsumei.ac.jp,"HTTPSConnectionPool(host='ritsumei.ac.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f12fce7a100>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ritsumei.ac.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12fb188e20>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
rivera.gub.uy,"HTTPSConnectionPool(host='rivera.gub.uy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='rivera.gub.uy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
riyadbank.com,"HTTPSConnectionPool(host='www.riyadbank.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.riyadbank.com', port=443): Read timed out. (read timeout=2)"
rmutr.ac.th,"HTTPSConnectionPool(host='rmutr.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f12fca507c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='rmutr.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12fbe13ee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
roditeljsrbija.com,"HTTPSConnectionPool(host='roditeljsrbija.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='roditeljsrbija.com', port=80): Read timed out. (read timeout=2)"
roundmenu.com,"HTTPSConnectionPool(host='www.roundmenu.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.roundmenu.com', port=443): Read timed out. (read timeout=2)"
rri.ro,"HTTPSConnectionPool(host='rri.ro', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'rri.ro' doesn't match 'www.rri.ro'"")))","HTTPSConnectionPool(host='www.rri.ro', port=443): Read timed out. (read timeout=2)"
rs-online.com,"HTTPSConnectionPool(host='rs-online.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f12fb117070>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='rs-online.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12fcbca3a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
rs.ba,"HTTPSConnectionPool(host='rs.ba', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f12fb21ed30>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='rs.ba', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12fb37a0a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
rtm.gov.my,"HTTPSConnectionPool(host='rtm.gov.my', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f12fcb7ff40>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='rtm.gov.my', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12fb16e2b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
rttuotetieto.fi,"HTTPSConnectionPool(host='rttuotetieto.fi', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'rttuotetieto.fi' doesn't match either of 'www.rttuotetieto.fi', 'urakoitsija.rttuotetieto.fi'"")))","HTTPSConnectionPool(host='www.rttuotetieto.fi', port=443): Read timed out. (read timeout=2)"
rtvmag.co.rs,"HTTPSConnectionPool(host='rtvmag.co.rs', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f12fbe131c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='rtvmag.co.rs', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12fc8b8250>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ru.ac.th,"HTTPSConnectionPool(host='ru.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f12fc9c2fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ru.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12fcae8820>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
rup.ee,"HTTPSConnectionPool(host='www.rup.ee', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.rup.ee', port=443): Read timed out. (read timeout=2)"
ruten.com.tw,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
rvb.lt,"HTTPSConnectionPool(host='rvb.lt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f12fb2a7e80>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='rvb.lt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12fc866760>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
rvo.nl,"HTTPSConnectionPool(host='www.rvo.nl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.rvo.nl', port=443): Read timed out. (read timeout=2)"
rvvg.lv,"HTTPSConnectionPool(host='rvvg.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.rvvg.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
rzp.cz,"HTTPSConnectionPool(host='rzp.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1124)')))","HTTPConnectionPool(host='rzp.cz', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f12fb2a71c0>, 'Connection to rzp.cz timed out. (connect timeout=2)'))"
saabturboclub.com,"HTTPSConnectionPool(host='saabturboclub.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f12fc969970>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='saabturboclub.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12fb3dae80>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
saaecearamirim.com.br,"HTTPSConnectionPool(host='saaecearamirim.com.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f12fce7a460>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='saaecearamirim.com.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12fc995310>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sabcnews.com,"HTTPSConnectionPool(host='www.sabcnews.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sabcnews.com', port=443): Read timed out. (read timeout=2)"
saberingles.com.ar,"HTTPSConnectionPool(host='saberingles.com.ar', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)')))",Exceeded 30 redirects.
sachvui.com,"HTTPSConnectionPool(host='sachvui.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='sachvui.com', port=443): Read timed out. (read timeout=2)"
sacombank.com.vn,"HTTPSConnectionPool(host='www.sacombank.com.vn', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sacombank.com.vn', port=443): Read timed out. (read timeout=2)"
saflii.org,"HTTPSConnectionPool(host='saflii.org', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.saflii.org', port=80): Read timed out. (read timeout=2)"
sahibinden.com,"HTTPSConnectionPool(host='sahibinden.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='sahibinden.com', port=80): Read timed out. (read timeout=2)"
sahibinden.com.tr,"HTTPSConnectionPool(host='sahibinden.com.tr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: TLSV1_UNRECOGNIZED_NAME] tlsv1 unrecognized name (_ssl.c:1124)')))","HTTPConnectionPool(host='sahibinden.com.tr', port=80): Read timed out. (read timeout=2)"
sahra.org.za,"HTTPSConnectionPool(host='sahra.org.za', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='sahra.org.za', port=80): Read timed out. (read timeout=2)"
saint-flour-communaute.fr,"HTTPSConnectionPool(host='saint-flour-communaute.fr', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='saint-flour-communaute.fr', port=80): Read timed out. (read timeout=2)"
saitama.lg.jp,"HTTPSConnectionPool(host='saitama.lg.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f12fbaaca90>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='saitama.lg.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12fbe2afa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
salernocorallorooms.it,"HTTPSConnectionPool(host='salernocorallorooms.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f12fa9df2e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='salernocorallorooms.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12fc846700>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
salika.co,"HTTPSConnectionPool(host='salika.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'salika.co' doesn't match 'www.salika.co'"")))","HTTPSConnectionPool(host='salika.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'salika.co' doesn't match 'www.salika.co'"")))"
salsaloca.be,"HTTPSConnectionPool(host='salsaloca.be', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f12fab05940>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='salsaloca.be', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12fcc71f40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
